<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/router/command/command.proto

namespace Xray\App\Router\Command;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use GPBMetadata\App\Router\Command\Command;

/**
 * Generated from protobuf message <code>xray.app.router.command.GetBalancerInfoResponse</code>
 */
class GetBalancerInfoResponse extends Message
{
    /**
     * Generated from protobuf field <code>.xray.app.router.command.BalancerMsg balancer = 1;</code>
     */
    protected $balancer = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * @type BalancerMsg $balancer
     * }
     */
    public function __construct($data = NULL)
    {
        Command::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.xray.app.router.command.BalancerMsg balancer = 1;</code>
     * @return BalancerMsg|null
     */
    public function getBalancer()
    {
        return $this->balancer;
    }

    public function hasBalancer()
    {
        return isset($this->balancer);
    }

    public function clearBalancer()
    {
        unset($this->balancer);
    }

    /**
     * Generated from protobuf field <code>.xray.app.router.command.BalancerMsg balancer = 1;</code>
     * @param BalancerMsg $var
     * @return $this
     */
    public function setBalancer($var)
    {
        GPBUtil::checkMessage($var, BalancerMsg::class);
        $this->balancer = $var;

        return $this;
    }

}

