<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/router/command/command.proto

namespace Xray\App\Router\Command;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use GPBMetadata\App\Router\Command\Command;

/**
 * Generated from protobuf message <code>xray.app.router.command.OverrideBalancerTargetRequest</code>
 */
class OverrideBalancerTargetRequest extends Message
{
    /**
     * Generated from protobuf field <code>string balancerTag = 1;</code>
     */
    protected $balancerTag = '';
    /**
     * Generated from protobuf field <code>string target = 2;</code>
     */
    protected $target = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * @type string $balancerTag
     * @type string $target
     * }
     */
    public function __construct($data = NULL)
    {
        Command::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string balancerTag = 1;</code>
     * @return string
     */
    public function getBalancerTag()
    {
        return $this->balancerTag;
    }

    /**
     * Generated from protobuf field <code>string balancerTag = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBalancerTag($var)
    {
        GPBUtil::checkString($var, True);
        $this->balancerTag = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string target = 2;</code>
     * @return string
     */
    public function getTarget()
    {
        return $this->target;
    }

    /**
     * Generated from protobuf field <code>string target = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTarget($var)
    {
        GPBUtil::checkString($var, True);
        $this->target = $var;

        return $this;
    }

}

