<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/router/command/command.proto

namespace Xray\App\Router\Command;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.app.router.command.RemoveRuleRequest</code>
 */
class RemoveRuleRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string ruleTag = 1;</code>
     */
    protected $ruleTag = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ruleTag
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Router\Command\Command::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string ruleTag = 1;</code>
     * @return string
     */
    public function getRuleTag()
    {
        return $this->ruleTag;
    }

    /**
     * Generated from protobuf field <code>string ruleTag = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRuleTag($var)
    {
        GPBUtil::checkString($var, True);
        $this->ruleTag = $var;

        return $this;
    }

}

