<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/router/command/command.proto

namespace Xray\App\Router\Command;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\MapField;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\Internal\RepeatedField;
use GPBMetadata\App\Router\Command\Command;
use Xray\Common\Net\Network;

/**
 * RoutingContext is the context with information relative to routing process.
 * It conforms to the structure of xray.features.routing.Context and
 * xray.features.routing.Route.
 *
 * Generated from protobuf message <code>xray.app.router.command.RoutingContext</code>
 */
class RoutingContext extends Message
{
    /**
     * Generated from protobuf field <code>string InboundTag = 1;</code>
     */
    protected $InboundTag = '';
    /**
     * Generated from protobuf field <code>.xray.common.net.Network Network = 2;</code>
     */
    protected $Network = 0;
    /**
     * Generated from protobuf field <code>repeated bytes SourceIPs = 3;</code>
     */
    private $SourceIPs;
    /**
     * Generated from protobuf field <code>repeated bytes TargetIPs = 4;</code>
     */
    private $TargetIPs;
    /**
     * Generated from protobuf field <code>uint32 SourcePort = 5;</code>
     */
    protected $SourcePort = 0;
    /**
     * Generated from protobuf field <code>uint32 TargetPort = 6;</code>
     */
    protected $TargetPort = 0;
    /**
     * Generated from protobuf field <code>string TargetDomain = 7;</code>
     */
    protected $TargetDomain = '';
    /**
     * Generated from protobuf field <code>string Protocol = 8;</code>
     */
    protected $Protocol = '';
    /**
     * Generated from protobuf field <code>string User = 9;</code>
     */
    protected $User = '';
    /**
     * Generated from protobuf field <code>map<string, string> Attributes = 10;</code>
     */
    private $Attributes;
    /**
     * Generated from protobuf field <code>repeated string OutboundGroupTags = 11;</code>
     */
    private $OutboundGroupTags;
    /**
     * Generated from protobuf field <code>string OutboundTag = 12;</code>
     */
    protected $OutboundTag = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * @type string $InboundTag
     * @type int $Network
     * @type array<string>|RepeatedField $SourceIPs
     * @type array<string>|RepeatedField $TargetIPs
     * @type int $SourcePort
     * @type int $TargetPort
     * @type string $TargetDomain
     * @type string $Protocol
     * @type string $User
     * @type array|MapField $Attributes
     * @type array<string>|RepeatedField $OutboundGroupTags
     * @type string $OutboundTag
     * }
     */
    public function __construct($data = NULL)
    {
        Command::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string InboundTag = 1;</code>
     * @return string
     */
    public function getInboundTag()
    {
        return $this->InboundTag;
    }

    /**
     * Generated from protobuf field <code>string InboundTag = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setInboundTag($var)
    {
        GPBUtil::checkString($var, True);
        $this->InboundTag = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.common.net.Network Network = 2;</code>
     * @return int
     */
    public function getNetwork()
    {
        return $this->Network;
    }

    /**
     * Generated from protobuf field <code>.xray.common.net.Network Network = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setNetwork($var)
    {
        GPBUtil::checkEnum($var, Network::class);
        $this->Network = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes SourceIPs = 3;</code>
     * @return RepeatedField
     */
    public function getSourceIPs()
    {
        return $this->SourceIPs;
    }

    /**
     * Generated from protobuf field <code>repeated bytes SourceIPs = 3;</code>
     * @param array<string>|RepeatedField $var
     * @return $this
     */
    public function setSourceIPs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::BYTES);
        $this->SourceIPs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes TargetIPs = 4;</code>
     * @return RepeatedField
     */
    public function getTargetIPs()
    {
        return $this->TargetIPs;
    }

    /**
     * Generated from protobuf field <code>repeated bytes TargetIPs = 4;</code>
     * @param array<string>|RepeatedField $var
     * @return $this
     */
    public function setTargetIPs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::BYTES);
        $this->TargetIPs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 SourcePort = 5;</code>
     * @return int
     */
    public function getSourcePort()
    {
        return $this->SourcePort;
    }

    /**
     * Generated from protobuf field <code>uint32 SourcePort = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setSourcePort($var)
    {
        GPBUtil::checkUint32($var);
        $this->SourcePort = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 TargetPort = 6;</code>
     * @return int
     */
    public function getTargetPort()
    {
        return $this->TargetPort;
    }

    /**
     * Generated from protobuf field <code>uint32 TargetPort = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setTargetPort($var)
    {
        GPBUtil::checkUint32($var);
        $this->TargetPort = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string TargetDomain = 7;</code>
     * @return string
     */
    public function getTargetDomain()
    {
        return $this->TargetDomain;
    }

    /**
     * Generated from protobuf field <code>string TargetDomain = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setTargetDomain($var)
    {
        GPBUtil::checkString($var, True);
        $this->TargetDomain = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Protocol = 8;</code>
     * @return string
     */
    public function getProtocol()
    {
        return $this->Protocol;
    }

    /**
     * Generated from protobuf field <code>string Protocol = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setProtocol($var)
    {
        GPBUtil::checkString($var, True);
        $this->Protocol = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string User = 9;</code>
     * @return string
     */
    public function getUser()
    {
        return $this->User;
    }

    /**
     * Generated from protobuf field <code>string User = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkString($var, True);
        $this->User = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> Attributes = 10;</code>
     * @return MapField
     */
    public function getAttributes()
    {
        return $this->Attributes;
    }

    /**
     * Generated from protobuf field <code>map<string, string> Attributes = 10;</code>
     * @param array|MapField $var
     * @return $this
     */
    public function setAttributes($var)
    {
        $arr = GPBUtil::checkMapField($var, GPBType::STRING, GPBType::STRING);
        $this->Attributes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string OutboundGroupTags = 11;</code>
     * @return RepeatedField
     */
    public function getOutboundGroupTags()
    {
        return $this->OutboundGroupTags;
    }

    /**
     * Generated from protobuf field <code>repeated string OutboundGroupTags = 11;</code>
     * @param array<string>|RepeatedField $var
     * @return $this
     */
    public function setOutboundGroupTags($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::STRING);
        $this->OutboundGroupTags = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string OutboundTag = 12;</code>
     * @return string
     */
    public function getOutboundTag()
    {
        return $this->OutboundTag;
    }

    /**
     * Generated from protobuf field <code>string OutboundTag = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setOutboundTag($var)
    {
        GPBUtil::checkString($var, True);
        $this->OutboundTag = $var;

        return $this;
    }

}

