<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/loopback/config.proto

namespace Xray\Proxy\Loopback;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.proxy.loopback.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string inbound_tag = 1;</code>
     */
    protected $inbound_tag = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $inbound_tag
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proxy\Loopback\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string inbound_tag = 1;</code>
     * @return string
     */
    public function getInboundTag()
    {
        return $this->inbound_tag;
    }

    /**
     * Generated from protobuf field <code>string inbound_tag = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setInboundTag($var)
    {
        GPBUtil::checkString($var, True);
        $this->inbound_tag = $var;

        return $this;
    }

}

