<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/splithttp/config.proto

namespace GPBMetadata\Transport\Internet\Splithttp;

use Google\Protobuf\Internal\DescriptorPool;

class Config
{
    public static $is_initialized = false;

    public static function initOnce()
    {
        $pool = DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
            return;
        }
        $pool->internalAddGeneratedFile(
            '
�
)transport/internet/splithttp/config.proto!xray.transport.internet.splithttp"�
Config
host (	
path (	E
header (25.xray.transport.internet.splithttp.Config.HeaderEntryP
scMaxConcurrentPosts (22.xray.transport.internet.splithttp.RandRangeConfigN
scMaxEachPostBytes (22.xray.transport.internet.splithttp.RandRangeConfigP
scMinPostsIntervalMs (22.xray.transport.internet.splithttp.RandRangeConfig
noSSEHeader (I

xPaddingBytes (22.xray.transport.internet.splithttp.RandRangeConfig=
xmux	 (2/.xray.transport.internet.splithttp.Multiplexing-
HeaderEntry
key (	
value (	:8"+
RandRangeConfig
from (

to ("�
MultiplexingJ
maxConcurrency (22.xray.transport.internet.splithttp.RandRangeConfigJ
maxConnections (22.xray.transport.internet.splithttp.RandRangeConfigJ
cMaxReuseTimes (22.xray.transport.internet.splithttp.RandRangeConfigJ
cMaxLifetimeMs (22.xray.transport.internet.splithttp.RandRangeConfigB�
%com.xray.transport.internet.splithttpPZ6github.com/xtls/xray-core/transport/internet/splithttp�!Xray.Transport.Internet.SplitHttpbproto3'
            , true);

        static::$is_initialized = true;
    }
}

