<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/udp/config.proto

namespace Xray\Transport\Internet\Udp;

use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>xray.transport.internet.udp.Config</code>
 */
class Config extends Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL)
    {
        \GPBMetadata\Transport\Internet\Udp\Config::initOnce();
        parent::__construct($data);
    }

}

