<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/policy/config.proto

namespace GPBMetadata\App\Policy;

use Google\Protobuf\Internal\DescriptorPool;

class Config
{
    public static $is_initialized = false;

    public static function initOnce()
    {
        $pool = DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
            return;
        }
        $pool->internalAddGeneratedFile(
            '
�
app/policy/config.protoxray.app.policy"
Second
value (
"�
Policy0
timeout (2.xray.app.policy.Policy.Timeout,
stats (2.xray.app.policy.Policy.Stats.
buffer (2.xray.app.policy.Policy.Buffer�
Timeout*
	handshake (2.xray.app.policy.Second0
connection_idle (2.xray.app.policy.Second,
uplink_only (2.xray.app.policy.Second.

downlink_only (2.xray.app.policy.Second3
Stats
user_uplink (

user_downlink (
Buffer

connection ("�
SystemPolicy2
stats (2#.xray.app.policy.SystemPolicy.Statsm
Stats
inbound_uplink (
inbound_downlink (
outbound_uplink (
outbound_downlink ("�
Config1
level (2".xray.app.policy.Config.LevelEntry-
system (2.xray.app.policy.SystemPolicyE

LevelEntry
key (
&
value (2.xray.app.policy.Policy:8BO
com.xray.app.policyPZ$github.com/xtls/xray-core/app/policy�Xray.App.Policybproto3'
            , true);

        static::$is_initialized = true;
    }
}

