<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/kcp/config.proto

namespace GPBMetadata\Transport\Internet\Kcp;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Serial\TypedMessage::initOnce();
        $pool->internalAddGeneratedFile(
            '
°
#transport/internet/kcp/config.protoxray.transport.internet.kcp"
MTU
value ("
TTI
value ("
UplinkCapacity
value ("!
DownlinkCapacity
value ("
WriteBuffer
size ("

ReadBuffer
size ("!
ConnectionReuse
enable ("
EncryptionSeed
seed (	"‚
Config-
mtu (2 .xray.transport.internet.kcp.MTU-
tti (2 .xray.transport.internet.kcp.TTID
uplink_capacity (2+.xray.transport.internet.kcp.UplinkCapacityH
downlink_capacity (2-.xray.transport.internet.kcp.DownlinkCapacity

congestion (>
write_buffer (2(.xray.transport.internet.kcp.WriteBuffer<
read_buffer (2\'.xray.transport.internet.kcp.ReadBuffer7
header_config (2 .xray.common.serial.TypedMessage9
seed
 (2+.xray.transport.internet.kcp.EncryptionSeedJ	
Bs
com.xray.transport.internet.kcpPZ0github.com/xtls/xray-core/transport/internet/kcpªXray.Transport.Internet.Kcpbproto3'
        , true);

        static::$is_initialized = true;
    }
}

