<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/dns/fakedns/fakedns.proto

namespace Xray\App\Dns\Fakedns;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.app.dns.fakedns.FakeDnsPool</code>
 */
class FakeDnsPool extends \Google\Protobuf\Internal\Message
{
    /**
     *CIDR of IP pool used as fake DNS IP
     *
     * Generated from protobuf field <code>string ip_pool = 1;</code>
     */
    protected $ip_pool = '';
    /**
     *Size of Pool for remembering relationship between domain name and IP address
     *
     * Generated from protobuf field <code>int64 lruSize = 2;</code>
     */
    protected $lruSize = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ip_pool
     *          CIDR of IP pool used as fake DNS IP
     *     @type int|string $lruSize
     *          Size of Pool for remembering relationship between domain name and IP address
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Dns\Fakedns\Fakedns::initOnce();
        parent::__construct($data);
    }

    /**
     *CIDR of IP pool used as fake DNS IP
     *
     * Generated from protobuf field <code>string ip_pool = 1;</code>
     * @return string
     */
    public function getIpPool()
    {
        return $this->ip_pool;
    }

    /**
     *CIDR of IP pool used as fake DNS IP
     *
     * Generated from protobuf field <code>string ip_pool = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setIpPool($var)
    {
        GPBUtil::checkString($var, True);
        $this->ip_pool = $var;

        return $this;
    }

    /**
     *Size of Pool for remembering relationship between domain name and IP address
     *
     * Generated from protobuf field <code>int64 lruSize = 2;</code>
     * @return int|string
     */
    public function getLruSize()
    {
        return $this->lruSize;
    }

    /**
     *Size of Pool for remembering relationship between domain name and IP address
     *
     * Generated from protobuf field <code>int64 lruSize = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLruSize($var)
    {
        GPBUtil::checkInt64($var);
        $this->lruSize = $var;

        return $this;
    }

}

