<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/shadowsocks_2022/config.proto

namespace GPBMetadata\Proxy\Shadowsocks2022;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Net\Network::initOnce();
        \GPBMetadata\Common\Net\Address::initOnce();
        $pool->internalAddGeneratedFile(
            '
Ñ
#proxy/shadowsocks_2022/config.protoxray.proxy.shadowsocks_2022common/net/address.proto"t
ServerConfig
method (	
key (	
email (	
level ()
network (2.xray.common.net.Network"‘
MultiUserServerConfig
method (	
key (	0
users (2!.xray.proxy.shadowsocks_2022.User)
network (2.xray.common.net.Network"y
RelayDestination
key (	,
address (2.xray.common.net.IPOrDomain
port (
email (	
level (" 
RelayServerConfig
method (	
key (	C
destinations (2-.xray.proxy.shadowsocks_2022.RelayDestination)
network (2.xray.common.net.Network"1
User
key (	
email (	
level ("›
ClientConfig,
address (2.xray.common.net.IPOrDomain
port (
method (	
key (	
udp_over_tcp (
udp_over_tcp_version (Br
com.xray.proxy.shadowsocks_2022PZ0github.com/xtls/xray-core/proxy/shadowsocks_2022ªXray.Proxy.Shadowsocks2022bproto3'
        , true);

        static::$is_initialized = true;
    }
}

