<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/vmess/outbound/config.proto

namespace GPBMetadata\Proxy\Vmess\Outbound;

use Google\Protobuf\Internal\DescriptorPool;
use GPBMetadata\Common\Protocol\ServerSpec;

class Config
{
    public static $is_initialized = false;

    public static function initOnce()
    {
        $pool = DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
            return;
        }
        ServerSpec::initOnce();
        $pool->internalAddGeneratedFile(
            '
�
!proxy/vmess/outbound/config.protoxray.proxy.vmess.outbound"@
Config6
Receiver (2$.xray.common.protocol.ServerEndpointBm
com.xray.proxy.vmess.outboundPZ.github.com/xtls/xray-core/proxy/vmess/outbound�Xray.Proxy.Vmess.Outboundbproto3'
            , true);

        static::$is_initialized = true;
    }
}

