<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/dns/config.proto

namespace Xray\App\Dns;

if (false) {
    /**
     * This class is deprecated. Use Xray\App\Dns\NameServer\OriginalRule instead.
     * @deprecated
     */
    class NameServer_OriginalRule
    {
    }
}
class_exists(NameServer\OriginalRule::class);
@trigger_error('Xray\App\Dns\NameServer_OriginalRule is deprecated and will be removed in the next major release. Use Xray\App\Dns\NameServer\OriginalRule instead', E_USER_DEPRECATED);

