<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/dns/config.proto

namespace Xray\App\Dns;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\Internal\RepeatedField;
use Xray\App\Dns\NameServer\OriginalRule;
use Xray\App\Dns\NameServer\PriorityDomain;
use Xray\App\Router\GeoIP;
use Xray\Common\Net\Endpoint;

/**
 * Generated from protobuf message <code>xray.app.dns.NameServer</code>
 */
class NameServer extends Message
{
    /**
     * Generated from protobuf field <code>.xray.common.net.Endpoint address = 1;</code>
     */
    protected $address = null;
    /**
     * Generated from protobuf field <code>bytes client_ip = 5;</code>
     */
    protected $client_ip = '';
    /**
     * Generated from protobuf field <code>bool skipFallback = 6;</code>
     */
    protected $skipFallback = false;
    /**
     * Generated from protobuf field <code>repeated .xray.app.dns.NameServer.PriorityDomain prioritized_domain = 2;</code>
     */
    private $prioritized_domain;
    /**
     * Generated from protobuf field <code>repeated .xray.app.router.GeoIP geoip = 3;</code>
     */
    private $geoip;
    /**
     * Generated from protobuf field <code>repeated .xray.app.dns.NameServer.OriginalRule original_rules = 4;</code>
     */
    private $original_rules;
    /**
     * Generated from protobuf field <code>.xray.app.dns.QueryStrategy query_strategy = 7;</code>
     */
    protected $query_strategy = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * @type Endpoint $address
     * @type string $client_ip
     * @type bool $skipFallback
     * @type array<PriorityDomain>|RepeatedField $prioritized_domain
     * @type array<GeoIP>|RepeatedField $geoip
     * @type array<OriginalRule>|RepeatedField $original_rules
     * @type int $query_strategy
     * }
     */
    public function __construct($data = NULL)
    {
        \GPBMetadata\App\Dns\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.xray.common.net.Endpoint address = 1;</code>
     * @return Endpoint|null
     */
    public function getAddress()
    {
        return $this->address;
    }

    public function hasAddress()
    {
        return isset($this->address);
    }

    public function clearAddress()
    {
        unset($this->address);
    }

    /**
     * Generated from protobuf field <code>.xray.common.net.Endpoint address = 1;</code>
     * @param Endpoint $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkMessage($var, Endpoint::class);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes client_ip = 5;</code>
     * @return string
     */
    public function getClientIp()
    {
        return $this->client_ip;
    }

    /**
     * Generated from protobuf field <code>bytes client_ip = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setClientIp($var)
    {
        GPBUtil::checkString($var, False);
        $this->client_ip = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool skipFallback = 6;</code>
     * @return bool
     */
    public function getSkipFallback()
    {
        return $this->skipFallback;
    }

    /**
     * Generated from protobuf field <code>bool skipFallback = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setSkipFallback($var)
    {
        GPBUtil::checkBool($var);
        $this->skipFallback = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.app.dns.NameServer.PriorityDomain prioritized_domain = 2;</code>
     * @return RepeatedField
     */
    public function getPrioritizedDomain()
    {
        return $this->prioritized_domain;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.app.dns.NameServer.PriorityDomain prioritized_domain = 2;</code>
     * @param array<PriorityDomain>|RepeatedField $var
     * @return $this
     */
    public function setPrioritizedDomain($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, PriorityDomain::class);
        $this->prioritized_domain = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.app.router.GeoIP geoip = 3;</code>
     * @return RepeatedField
     */
    public function getGeoip()
    {
        return $this->geoip;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.app.router.GeoIP geoip = 3;</code>
     * @param array<GeoIP>|RepeatedField $var
     * @return $this
     */
    public function setGeoip($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, GeoIP::class);
        $this->geoip = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.app.dns.NameServer.OriginalRule original_rules = 4;</code>
     * @return RepeatedField
     */
    public function getOriginalRules()
    {
        return $this->original_rules;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.app.dns.NameServer.OriginalRule original_rules = 4;</code>
     * @param array<OriginalRule>|RepeatedField $var
     * @return $this
     */
    public function setOriginalRules($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, OriginalRule::class);
        $this->original_rules = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.app.dns.QueryStrategy query_strategy = 7;</code>
     * @return int
     */
    public function getQueryStrategy()
    {
        return $this->query_strategy;
    }

    /**
     * Generated from protobuf field <code>.xray.app.dns.QueryStrategy query_strategy = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setQueryStrategy($var)
    {
        GPBUtil::checkEnum($var, QueryStrategy::class);
        $this->query_strategy = $var;

        return $this;
    }

}

