<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/dns/config.proto

namespace Xray\App\Dns;

if (false) {
    /**
     * This class is deprecated. Use Xray\App\Dns\NameServer\PriorityDomain instead.
     * @deprecated
     */
    class NameServer_PriorityDomain
    {
    }
}
class_exists(NameServer\PriorityDomain::class);
@trigger_error('Xray\App\Dns\NameServer_PriorityDomain is deprecated and will be removed in the next major release. Use Xray\App\Dns\NameServer\PriorityDomain instead', E_USER_DEPRECATED);

