<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/headers/http/config.proto

namespace Xray\Transport\Internet\Headers\Http;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.transport.internet.headers.http.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Settings for authenticating requests. If not set, client side will not send
     * authentication header, and server side will bypass authentication.
     *
     * Generated from protobuf field <code>.xray.transport.internet.headers.http.RequestConfig request = 1;</code>
     */
    protected $request = null;
    /**
     * Settings for authenticating responses. If not set, client side will bypass
     * authentication, and server side will not send authentication header.
     *
     * Generated from protobuf field <code>.xray.transport.internet.headers.http.ResponseConfig response = 2;</code>
     */
    protected $response = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Xray\Transport\Internet\Headers\Http\RequestConfig $request
     *           Settings for authenticating requests. If not set, client side will not send
     *           authentication header, and server side will bypass authentication.
     *     @type \Xray\Transport\Internet\Headers\Http\ResponseConfig $response
     *           Settings for authenticating responses. If not set, client side will bypass
     *           authentication, and server side will not send authentication header.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transport\Internet\Headers\Http\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Settings for authenticating requests. If not set, client side will not send
     * authentication header, and server side will bypass authentication.
     *
     * Generated from protobuf field <code>.xray.transport.internet.headers.http.RequestConfig request = 1;</code>
     * @return \Xray\Transport\Internet\Headers\Http\RequestConfig|null
     */
    public function getRequest()
    {
        return $this->request;
    }

    public function hasRequest()
    {
        return isset($this->request);
    }

    public function clearRequest()
    {
        unset($this->request);
    }

    /**
     * Settings for authenticating requests. If not set, client side will not send
     * authentication header, and server side will bypass authentication.
     *
     * Generated from protobuf field <code>.xray.transport.internet.headers.http.RequestConfig request = 1;</code>
     * @param \Xray\Transport\Internet\Headers\Http\RequestConfig $var
     * @return $this
     */
    public function setRequest($var)
    {
        GPBUtil::checkMessage($var, \Xray\Transport\Internet\Headers\Http\RequestConfig::class);
        $this->request = $var;

        return $this;
    }

    /**
     * Settings for authenticating responses. If not set, client side will bypass
     * authentication, and server side will not send authentication header.
     *
     * Generated from protobuf field <code>.xray.transport.internet.headers.http.ResponseConfig response = 2;</code>
     * @return \Xray\Transport\Internet\Headers\Http\ResponseConfig|null
     */
    public function getResponse()
    {
        return $this->response;
    }

    public function hasResponse()
    {
        return isset($this->response);
    }

    public function clearResponse()
    {
        unset($this->response);
    }

    /**
     * Settings for authenticating responses. If not set, client side will bypass
     * authentication, and server side will not send authentication header.
     *
     * Generated from protobuf field <code>.xray.transport.internet.headers.http.ResponseConfig response = 2;</code>
     * @param \Xray\Transport\Internet\Headers\Http\ResponseConfig $var
     * @return $this
     */
    public function setResponse($var)
    {
        GPBUtil::checkMessage($var, \Xray\Transport\Internet\Headers\Http\ResponseConfig::class);
        $this->response = $var;

        return $this;
    }

}

