<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/headers/http/config.proto

namespace Xray\Transport\Internet\Headers\Http;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\Internal\RepeatedField;

/**
 * Generated from protobuf message <code>xray.transport.internet.headers.http.RequestConfig</code>
 */
class RequestConfig extends Message
{
    /**
     * Full HTTP version like "1.1".
     *
     * Generated from protobuf field <code>.xray.transport.internet.headers.http.Version version = 1;</code>
     */
    protected $version = null;
    /**
     * GET, POST, CONNECT etc
     *
     * Generated from protobuf field <code>.xray.transport.internet.headers.http.Method method = 2;</code>
     */
    protected $method = null;
    /**
     * URI like "/login.php"
     *
     * Generated from protobuf field <code>repeated string uri = 3;</code>
     */
    private $uri;
    /**
     * Generated from protobuf field <code>repeated .xray.transport.internet.headers.http.Header header = 4;</code>
     */
    private $header;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * @type Version $version
     *           Full HTTP version like "1.1".
     * @type Method $method
     *           GET, POST, CONNECT etc
     * @type array<string>|RepeatedField $uri
     *           URI like "/login.php"
     * @type array<Header>|RepeatedField $header
     * }
     */
    public function __construct($data = NULL)
    {
        \GPBMetadata\Transport\Internet\Headers\Http\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Full HTTP version like "1.1".
     *
     * Generated from protobuf field <code>.xray.transport.internet.headers.http.Version version = 1;</code>
     * @return Version|null
     */
    public function getVersion()
    {
        return $this->version;
    }

    public function hasVersion()
    {
        return isset($this->version);
    }

    public function clearVersion()
    {
        unset($this->version);
    }

    /**
     * Full HTTP version like "1.1".
     *
     * Generated from protobuf field <code>.xray.transport.internet.headers.http.Version version = 1;</code>
     * @param Version $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkMessage($var, Version::class);
        $this->version = $var;

        return $this;
    }

    /**
     * GET, POST, CONNECT etc
     *
     * Generated from protobuf field <code>.xray.transport.internet.headers.http.Method method = 2;</code>
     * @return Method|null
     */
    public function getMethod()
    {
        return $this->method;
    }

    public function hasMethod()
    {
        return isset($this->method);
    }

    public function clearMethod()
    {
        unset($this->method);
    }

    /**
     * GET, POST, CONNECT etc
     *
     * Generated from protobuf field <code>.xray.transport.internet.headers.http.Method method = 2;</code>
     * @param Method $var
     * @return $this
     */
    public function setMethod($var)
    {
        GPBUtil::checkMessage($var, Method::class);
        $this->method = $var;

        return $this;
    }

    /**
     * URI like "/login.php"
     *
     * Generated from protobuf field <code>repeated string uri = 3;</code>
     * @return RepeatedField
     */
    public function getUri()
    {
        return $this->uri;
    }

    /**
     * URI like "/login.php"
     *
     * Generated from protobuf field <code>repeated string uri = 3;</code>
     * @param array<string>|RepeatedField $var
     * @return $this
     */
    public function setUri($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::STRING);
        $this->uri = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.transport.internet.headers.http.Header header = 4;</code>
     * @return RepeatedField
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.transport.internet.headers.http.Header header = 4;</code>
     * @param array<Header>|RepeatedField $var
     * @return $this
     */
    public function setHeader($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Header::class);
        $this->header = $arr;

        return $this;
    }

}

