<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/headers/http/config.proto

namespace Xray\Transport\Internet\Headers\Http;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.transport.internet.headers.http.ResponseConfig</code>
 */
class ResponseConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.xray.transport.internet.headers.http.Version version = 1;</code>
     */
    protected $version = null;
    /**
     * Generated from protobuf field <code>.xray.transport.internet.headers.http.Status status = 2;</code>
     */
    protected $status = null;
    /**
     * Generated from protobuf field <code>repeated .xray.transport.internet.headers.http.Header header = 3;</code>
     */
    private $header;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Xray\Transport\Internet\Headers\Http\Version $version
     *     @type \Xray\Transport\Internet\Headers\Http\Status $status
     *     @type array<\Xray\Transport\Internet\Headers\Http\Header>|\Google\Protobuf\Internal\RepeatedField $header
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transport\Internet\Headers\Http\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.headers.http.Version version = 1;</code>
     * @return \Xray\Transport\Internet\Headers\Http\Version|null
     */
    public function getVersion()
    {
        return $this->version;
    }

    public function hasVersion()
    {
        return isset($this->version);
    }

    public function clearVersion()
    {
        unset($this->version);
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.headers.http.Version version = 1;</code>
     * @param \Xray\Transport\Internet\Headers\Http\Version $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkMessage($var, \Xray\Transport\Internet\Headers\Http\Version::class);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.headers.http.Status status = 2;</code>
     * @return \Xray\Transport\Internet\Headers\Http\Status|null
     */
    public function getStatus()
    {
        return $this->status;
    }

    public function hasStatus()
    {
        return isset($this->status);
    }

    public function clearStatus()
    {
        unset($this->status);
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.headers.http.Status status = 2;</code>
     * @param \Xray\Transport\Internet\Headers\Http\Status $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkMessage($var, \Xray\Transport\Internet\Headers\Http\Status::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.transport.internet.headers.http.Header header = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.transport.internet.headers.http.Header header = 3;</code>
     * @param array<\Xray\Transport\Internet\Headers\Http\Header>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHeader($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xray\Transport\Internet\Headers\Http\Header::class);
        $this->header = $arr;

        return $this;
    }

}

