<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/stats/config.proto

namespace Xray\App\Stats;

use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>xray.app.stats.Config</code>
 */
class Config extends Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL)
    {
        \GPBMetadata\App\Stats\Config::initOnce();
        parent::__construct($data);
    }

}

