<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/dokodemo/config.proto

namespace Xray\Proxy\Dokodemo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\Internal\RepeatedField;
use Xray\Common\Net\IPOrDomain;
use Xray\Common\Net\Network;

/**
 * Generated from protobuf message <code>xray.proxy.dokodemo.Config</code>
 */
class Config extends Message
{
    /**
     * Generated from protobuf field <code>.xray.common.net.IPOrDomain address = 1;</code>
     */
    protected $address = null;
    /**
     * Generated from protobuf field <code>uint32 port = 2;</code>
     */
    protected $port = 0;
    /**
     * List of networks that the Dokodemo accepts.
     *
     * Generated from protobuf field <code>repeated .xray.common.net.Network networks = 7;</code>
     */
    private $networks;
    /**
     * Generated from protobuf field <code>bool follow_redirect = 5;</code>
     */
    protected $follow_redirect = false;
    /**
     * Generated from protobuf field <code>uint32 user_level = 6;</code>
     */
    protected $user_level = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * @type IPOrDomain $address
     * @type int $port
     * @type array<int>|RepeatedField $networks
     *           List of networks that the Dokodemo accepts.
     * @type bool $follow_redirect
     * @type int $user_level
     * }
     */
    public function __construct($data = NULL)
    {
        \GPBMetadata\Proxy\Dokodemo\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.xray.common.net.IPOrDomain address = 1;</code>
     * @return IPOrDomain|null
     */
    public function getAddress()
    {
        return $this->address;
    }

    public function hasAddress()
    {
        return isset($this->address);
    }

    public function clearAddress()
    {
        unset($this->address);
    }

    /**
     * Generated from protobuf field <code>.xray.common.net.IPOrDomain address = 1;</code>
     * @param IPOrDomain $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkMessage($var, IPOrDomain::class);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 port = 2;</code>
     * @return int
     */
    public function getPort()
    {
        return $this->port;
    }

    /**
     * Generated from protobuf field <code>uint32 port = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPort($var)
    {
        GPBUtil::checkUint32($var);
        $this->port = $var;

        return $this;
    }

    /**
     * List of networks that the Dokodemo accepts.
     *
     * Generated from protobuf field <code>repeated .xray.common.net.Network networks = 7;</code>
     * @return RepeatedField
     */
    public function getNetworks()
    {
        return $this->networks;
    }

    /**
     * List of networks that the Dokodemo accepts.
     *
     * Generated from protobuf field <code>repeated .xray.common.net.Network networks = 7;</code>
     * @param array<int>|RepeatedField $var
     * @return $this
     */
    public function setNetworks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::ENUM, Network::class);
        $this->networks = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool follow_redirect = 5;</code>
     * @return bool
     */
    public function getFollowRedirect()
    {
        return $this->follow_redirect;
    }

    /**
     * Generated from protobuf field <code>bool follow_redirect = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setFollowRedirect($var)
    {
        GPBUtil::checkBool($var);
        $this->follow_redirect = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 user_level = 6;</code>
     * @return int
     */
    public function getUserLevel()
    {
        return $this->user_level;
    }

    /**
     * Generated from protobuf field <code>uint32 user_level = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setUserLevel($var)
    {
        GPBUtil::checkUint32($var);
        $this->user_level = $var;

        return $this;
    }

}

