<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/vless/outbound/config.proto

namespace Xray\Proxy\Vless\Outbound;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\Internal\RepeatedField;
use Xray\Common\Protocol\ServerEndpoint;

/**
 * Generated from protobuf message <code>xray.proxy.vless.outbound.Config</code>
 */
class Config extends Message
{
    /**
     * Generated from protobuf field <code>repeated .xray.common.protocol.ServerEndpoint vnext = 1;</code>
     */
    private $vnext;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * @type array<ServerEndpoint>|RepeatedField $vnext
     * }
     */
    public function __construct($data = NULL)
    {
        \GPBMetadata\Proxy\Vless\Outbound\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.protocol.ServerEndpoint vnext = 1;</code>
     * @return RepeatedField
     */
    public function getVnext()
    {
        return $this->vnext;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.protocol.ServerEndpoint vnext = 1;</code>
     * @param array<ServerEndpoint>|RepeatedField $var
     * @return $this
     */
    public function setVnext($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, ServerEndpoint::class);
        $this->vnext = $arr;

        return $this;
    }

}

