<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/tls/config.proto

namespace Xray\Transport\Internet\Tls;

if (false) {
    /**
     * This class is deprecated. Use Xray\Transport\Internet\Tls\Certificate\Usage instead.
     * @deprecated
     */
    class Certificate_Usage
    {
    }
}
class_exists(Certificate\Usage::class);
@trigger_error('Xray\Transport\Internet\Tls\Certificate_Usage is deprecated and will be removed in the next major release. Use Xray\Transport\Internet\Tls\Certificate\Usage instead', E_USER_DEPRECATED);

