<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/vmess/inbound/config.proto

namespace Xray\Proxy\Vmess\Inbound;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\Internal\RepeatedField;
use Xray\Common\Protocol\User;

/**
 * Generated from protobuf message <code>xray.proxy.vmess.inbound.Config</code>
 */
class Config extends Message
{
    /**
     * Generated from protobuf field <code>repeated .xray.common.protocol.User user = 1;</code>
     */
    private $user;
    /**
     * Generated from protobuf field <code>.xray.proxy.vmess.inbound.DefaultConfig default = 2;</code>
     */
    protected $default = null;
    /**
     * 4 is for legacy setting
     *
     * Generated from protobuf field <code>.xray.proxy.vmess.inbound.DetourConfig detour = 3;</code>
     */
    protected $detour = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * @type array<User>|RepeatedField $user
     * @type DefaultConfig $default
     * @type DetourConfig $detour
     *           4 is for legacy setting
     * }
     */
    public function __construct($data = NULL)
    {
        \GPBMetadata\Proxy\Vmess\Inbound\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.protocol.User user = 1;</code>
     * @return RepeatedField
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.protocol.User user = 1;</code>
     * @param array<User>|RepeatedField $var
     * @return $this
     */
    public function setUser($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, User::class);
        $this->user = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.proxy.vmess.inbound.DefaultConfig default = 2;</code>
     * @return DefaultConfig|null
     */
    public function getDefault()
    {
        return $this->default;
    }

    public function hasDefault()
    {
        return isset($this->default);
    }

    public function clearDefault()
    {
        unset($this->default);
    }

    /**
     * Generated from protobuf field <code>.xray.proxy.vmess.inbound.DefaultConfig default = 2;</code>
     * @param DefaultConfig $var
     * @return $this
     */
    public function setDefault($var)
    {
        GPBUtil::checkMessage($var, DefaultConfig::class);
        $this->default = $var;

        return $this;
    }

    /**
     * 4 is for legacy setting
     *
     * Generated from protobuf field <code>.xray.proxy.vmess.inbound.DetourConfig detour = 3;</code>
     * @return DetourConfig|null
     */
    public function getDetour()
    {
        return $this->detour;
    }

    public function hasDetour()
    {
        return isset($this->detour);
    }

    public function clearDetour()
    {
        unset($this->detour);
    }

    /**
     * 4 is for legacy setting
     *
     * Generated from protobuf field <code>.xray.proxy.vmess.inbound.DetourConfig detour = 3;</code>
     * @param DetourConfig $var
     * @return $this
     */
    public function setDetour($var)
    {
        GPBUtil::checkMessage($var, DetourConfig::class);
        $this->detour = $var;

        return $this;
    }

}

