<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/vmess/inbound/config.proto

namespace Xray\Proxy\Vmess\Inbound;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.proxy.vmess.inbound.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .xray.common.protocol.User user = 1;</code>
     */
    private $user;
    /**
     * Generated from protobuf field <code>.xray.proxy.vmess.inbound.DefaultConfig default = 2;</code>
     */
    protected $default = null;
    /**
     * 4 is for legacy setting
     *
     * Generated from protobuf field <code>.xray.proxy.vmess.inbound.DetourConfig detour = 3;</code>
     */
    protected $detour = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Xray\Common\Protocol\User>|\Google\Protobuf\Internal\RepeatedField $user
     *     @type \Xray\Proxy\Vmess\Inbound\DefaultConfig $default
     *     @type \Xray\Proxy\Vmess\Inbound\DetourConfig $detour
     *           4 is for legacy setting
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proxy\Vmess\Inbound\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.protocol.User user = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.protocol.User user = 1;</code>
     * @param array<\Xray\Common\Protocol\User>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUser($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xray\Common\Protocol\User::class);
        $this->user = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.proxy.vmess.inbound.DefaultConfig default = 2;</code>
     * @return \Xray\Proxy\Vmess\Inbound\DefaultConfig|null
     */
    public function getDefault()
    {
        return $this->default;
    }

    public function hasDefault()
    {
        return isset($this->default);
    }

    public function clearDefault()
    {
        unset($this->default);
    }

    /**
     * Generated from protobuf field <code>.xray.proxy.vmess.inbound.DefaultConfig default = 2;</code>
     * @param \Xray\Proxy\Vmess\Inbound\DefaultConfig $var
     * @return $this
     */
    public function setDefault($var)
    {
        GPBUtil::checkMessage($var, \Xray\Proxy\Vmess\Inbound\DefaultConfig::class);
        $this->default = $var;

        return $this;
    }

    /**
     * 4 is for legacy setting
     *
     * Generated from protobuf field <code>.xray.proxy.vmess.inbound.DetourConfig detour = 3;</code>
     * @return \Xray\Proxy\Vmess\Inbound\DetourConfig|null
     */
    public function getDetour()
    {
        return $this->detour;
    }

    public function hasDetour()
    {
        return isset($this->detour);
    }

    public function clearDetour()
    {
        unset($this->detour);
    }

    /**
     * 4 is for legacy setting
     *
     * Generated from protobuf field <code>.xray.proxy.vmess.inbound.DetourConfig detour = 3;</code>
     * @param \Xray\Proxy\Vmess\Inbound\DetourConfig $var
     * @return $this
     */
    public function setDetour($var)
    {
        GPBUtil::checkMessage($var, \Xray\Proxy\Vmess\Inbound\DetourConfig::class);
        $this->detour = $var;

        return $this;
    }

}

