<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/vmess/inbound/config.proto

namespace Xray\Proxy\Vmess\Inbound;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.proxy.vmess.inbound.DefaultConfig</code>
 */
class DefaultConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 level = 2;</code>
     */
    protected $level = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $level
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proxy\Vmess\Inbound\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 level = 2;</code>
     * @return int
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     * Generated from protobuf field <code>uint32 level = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setLevel($var)
    {
        GPBUtil::checkUint32($var);
        $this->level = $var;

        return $this;
    }

}

