<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/headers/http/config.proto

namespace GPBMetadata\Transport\Internet\Headers\Http;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
²
,transport/internet/headers/http/config.proto$xray.transport.internet.headers.http"%
Header
name (	
value (	"
Version
value (	"
Method
value (	"Ø
RequestConfig>
version (2-.xray.transport.internet.headers.http.Version<
method (2,.xray.transport.internet.headers.http.Method
uri (	<
header (2,.xray.transport.internet.headers.http.Header"&
Status
code (	
reason (	"Ì
ResponseConfig>
version (2-.xray.transport.internet.headers.http.Version<
status (2,.xray.transport.internet.headers.http.Status<
header (2,.xray.transport.internet.headers.http.Header"–
ConfigD
request (23.xray.transport.internet.headers.http.RequestConfigF
response (24.xray.transport.internet.headers.http.ResponseConfigB
(com.xray.transport.internet.headers.httpPZ9github.com/xtls/xray-core/transport/internet/headers/httpª$Xray.Transport.Internet.Headers.Httpbproto3'
        , true);

        static::$is_initialized = true;
    }
}

