<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/router/config.proto

namespace Xray\App\Router;

if (false) {
    /**
     * This class is deprecated. Use Xray\App\Router\Config\DomainStrategy instead.
     * @deprecated
     */
    class Config_DomainStrategy
    {
    }
}
class_exists(Config\DomainStrategy::class);
@trigger_error('Xray\App\Router\Config_DomainStrategy is deprecated and will be removed in the next major release. Use Xray\App\Router\Config\DomainStrategy instead', E_USER_DEPRECATED);

