<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/router/config.proto

namespace Xray\App\Router;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.app.router.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.xray.app.router.Config.DomainStrategy domain_strategy = 1;</code>
     */
    protected $domain_strategy = 0;
    /**
     * Generated from protobuf field <code>repeated .xray.app.router.RoutingRule rule = 2;</code>
     */
    private $rule;
    /**
     * Generated from protobuf field <code>repeated .xray.app.router.BalancingRule balancing_rule = 3;</code>
     */
    private $balancing_rule;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $domain_strategy
     *     @type array<\Xray\App\Router\RoutingRule>|\Google\Protobuf\Internal\RepeatedField $rule
     *     @type array<\Xray\App\Router\BalancingRule>|\Google\Protobuf\Internal\RepeatedField $balancing_rule
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Router\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.xray.app.router.Config.DomainStrategy domain_strategy = 1;</code>
     * @return int
     */
    public function getDomainStrategy()
    {
        return $this->domain_strategy;
    }

    /**
     * Generated from protobuf field <code>.xray.app.router.Config.DomainStrategy domain_strategy = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setDomainStrategy($var)
    {
        GPBUtil::checkEnum($var, \Xray\App\Router\Config\DomainStrategy::class);
        $this->domain_strategy = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.app.router.RoutingRule rule = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRule()
    {
        return $this->rule;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.app.router.RoutingRule rule = 2;</code>
     * @param array<\Xray\App\Router\RoutingRule>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRule($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xray\App\Router\RoutingRule::class);
        $this->rule = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.app.router.BalancingRule balancing_rule = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBalancingRule()
    {
        return $this->balancing_rule;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.app.router.BalancingRule balancing_rule = 3;</code>
     * @param array<\Xray\App\Router\BalancingRule>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBalancingRule($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xray\App\Router\BalancingRule::class);
        $this->balancing_rule = $arr;

        return $this;
    }

}

