<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/router/config.proto

namespace Xray\App\Router;

if (false) {
    /**
     * This class is deprecated. Use Xray\App\Router\Domain\Type instead.
     * @deprecated
     */
    class Domain_Type
    {
    }
}
class_exists(Domain\Type::class);
@trigger_error('Xray\App\Router\Domain_Type is deprecated and will be removed in the next major release. Use Xray\App\Router\Domain\Type instead', E_USER_DEPRECATED);

