<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/router/config.proto

namespace Xray\App\Router;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.app.router.StrategyWeight</code>
 */
class StrategyWeight extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool regexp = 1;</code>
     */
    protected $regexp = false;
    /**
     * Generated from protobuf field <code>string match = 2;</code>
     */
    protected $match = '';
    /**
     * Generated from protobuf field <code>float value = 3;</code>
     */
    protected $value = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $regexp
     *     @type string $match
     *     @type float $value
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Router\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool regexp = 1;</code>
     * @return bool
     */
    public function getRegexp()
    {
        return $this->regexp;
    }

    /**
     * Generated from protobuf field <code>bool regexp = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setRegexp($var)
    {
        GPBUtil::checkBool($var);
        $this->regexp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string match = 2;</code>
     * @return string
     */
    public function getMatch()
    {
        return $this->match;
    }

    /**
     * Generated from protobuf field <code>string match = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMatch($var)
    {
        GPBUtil::checkString($var, True);
        $this->match = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float value = 3;</code>
     * @return float
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>float value = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkFloat($var);
        $this->value = $var;

        return $this;
    }

}

