<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/proxyman/command/command.proto

namespace Xray\App\Proxyman\Command;

use Google\Protobuf\Internal\Message;
use GPBMetadata\App\Proxyman\Command\Command;

/**
 * Generated from protobuf message <code>xray.app.proxyman.command.AlterInboundResponse</code>
 */
class AlterInboundResponse extends Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL)
    {
        Command::initOnce();
        parent::__construct($data);
    }

}

