<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/headers/noop/config.proto

namespace GPBMetadata\Transport\Internet\Headers\Noop;

use Google\Protobuf\Internal\DescriptorPool;

class Config
{
    public static $is_initialized = false;

    public static function initOnce()
    {
        $pool = DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
            return;
        }
        $pool->internalAddGeneratedFile(
            '
�
,transport/internet/headers/noop/config.proto$xray.transport.internet.headers.noop"
Config"
ConnectionConfigB�
(com.xray.transport.internet.headers.noopPZ9github.com/xtls/xray-core/transport/internet/headers/noop�$Xray.Transport.Internet.Headers.Noopbproto3'
            , true);

        static::$is_initialized = true;
    }
}

