<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/headers/noop/config.proto

namespace GPBMetadata\Transport\Internet\Headers\Noop;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
‹
,transport/internet/headers/noop/config.proto$xray.transport.internet.headers.noop"
Config"
ConnectionConfigBŽ
(com.xray.transport.internet.headers.noopPZ9github.com/xtls/xray-core/transport/internet/headers/noopª$Xray.Transport.Internet.Headers.Noopbproto3'
        , true);

        static::$is_initialized = true;
    }
}

