<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/trojan/config.proto

namespace GPBMetadata\Proxy\Trojan;

use Google\Protobuf\Internal\DescriptorPool;
use GPBMetadata\Common\Protocol\ServerSpec;
use GPBMetadata\Common\Protocol\User;

class Config
{
    public static $is_initialized = false;

    public static function initOnce()
    {
        $pool = DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
            return;
        }
        User::initOnce();
        ServerSpec::initOnce();
        $pool->internalAddGeneratedFile(
            '
�
proxy/trojan/config.protoxray.proxy.trojan!common/protocol/server_spec.proto"
Account
password (	"^
Fallback
name (	
alpn (	
path (	
type (	
dest (	
xver ("D
ClientConfig4
server (2$.xray.common.protocol.ServerEndpoint"i
ServerConfig)
users (2.xray.common.protocol.User.
	fallbacks (2.xray.proxy.trojan.FallbackBU
com.xray.proxy.trojanPZ&github.com/xtls/xray-core/proxy/trojan�Xray.Proxy.Trojanbproto3'
            , true);

        static::$is_initialized = true;
    }
}

