<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/trojan/config.proto

namespace GPBMetadata\Proxy\Trojan;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Protocol\User::initOnce();
        \GPBMetadata\Common\Protocol\ServerSpec::initOnce();
        $pool->internalAddGeneratedFile(
            '
Þ
proxy/trojan/config.protoxray.proxy.trojan!common/protocol/server_spec.proto"
Account
password (	"^
Fallback
name (	
alpn (	
path (	
type (	
dest (	
xver ("D
ClientConfig4
server (2$.xray.common.protocol.ServerEndpoint"i
ServerConfig)
users (2.xray.common.protocol.User.
	fallbacks (2.xray.proxy.trojan.FallbackBU
com.xray.proxy.trojanPZ&github.com/xtls/xray-core/proxy/trojanªXray.Proxy.Trojanbproto3'
        , true);

        static::$is_initialized = true;
    }
}

