<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/net/port.proto

namespace Xray\Common\Net;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\Internal\RepeatedField;
use GPBMetadata\Common\Net\Port;

/**
 * PortList is a list of ports.
 *
 * Generated from protobuf message <code>xray.common.net.PortList</code>
 */
class PortList extends Message
{
    /**
     * Generated from protobuf field <code>repeated .xray.common.net.PortRange range = 1;</code>
     */
    private $range;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * @type array<PortRange>|RepeatedField $range
     * }
     */
    public function __construct($data = NULL)
    {
        Port::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.net.PortRange range = 1;</code>
     * @return RepeatedField
     */
    public function getRange()
    {
        return $this->range;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.net.PortRange range = 1;</code>
     * @param array<PortRange>|RepeatedField $var
     * @return $this
     */
    public function setRange($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, PortRange::class);
        $this->range = $arr;

        return $this;
    }

}

