<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/tcp/config.proto

namespace Xray\Transport\Internet\Tcp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.transport.internet.tcp.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.xray.common.serial.TypedMessage header_settings = 2;</code>
     */
    protected $header_settings = null;
    /**
     * Generated from protobuf field <code>bool accept_proxy_protocol = 3;</code>
     */
    protected $accept_proxy_protocol = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Xray\Common\Serial\TypedMessage $header_settings
     *     @type bool $accept_proxy_protocol
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transport\Internet\Tcp\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.xray.common.serial.TypedMessage header_settings = 2;</code>
     * @return \Xray\Common\Serial\TypedMessage|null
     */
    public function getHeaderSettings()
    {
        return $this->header_settings;
    }

    public function hasHeaderSettings()
    {
        return isset($this->header_settings);
    }

    public function clearHeaderSettings()
    {
        unset($this->header_settings);
    }

    /**
     * Generated from protobuf field <code>.xray.common.serial.TypedMessage header_settings = 2;</code>
     * @param \Xray\Common\Serial\TypedMessage $var
     * @return $this
     */
    public function setHeaderSettings($var)
    {
        GPBUtil::checkMessage($var, \Xray\Common\Serial\TypedMessage::class);
        $this->header_settings = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool accept_proxy_protocol = 3;</code>
     * @return bool
     */
    public function getAcceptProxyProtocol()
    {
        return $this->accept_proxy_protocol;
    }

    /**
     * Generated from protobuf field <code>bool accept_proxy_protocol = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setAcceptProxyProtocol($var)
    {
        GPBUtil::checkBool($var);
        $this->accept_proxy_protocol = $var;

        return $this;
    }

}

