<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/stats/command/command.proto

namespace Xray\App\Stats\Command;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\Internal\RepeatedField;
use GPBMetadata\App\Stats\Command\Command;

/**
 * Generated from protobuf message <code>xray.app.stats.command.QueryStatsResponse</code>
 */
class QueryStatsResponse extends Message
{
    /**
     * Generated from protobuf field <code>repeated .xray.app.stats.command.Stat stat = 1;</code>
     */
    private $stat;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * @type array<Stat>|RepeatedField $stat
     * }
     */
    public function __construct($data = NULL)
    {
        Command::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .xray.app.stats.command.Stat stat = 1;</code>
     * @return RepeatedField
     */
    public function getStat()
    {
        return $this->stat;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.app.stats.command.Stat stat = 1;</code>
     * @param array<Stat>|RepeatedField $var
     * @return $this
     */
    public function setStat($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Stat::class);
        $this->stat = $arr;

        return $this;
    }

}

