<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/udp/config.proto

namespace GPBMetadata\Transport\Internet\Udp;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
É
#transport/internet/udp/config.protoxray.transport.internet.udp"
ConfigBs
com.xray.transport.internet.udpPZ0github.com/xtls/xray-core/transport/internet/udpªXray.Transport.Internet.Udpbproto3'
        , true);

        static::$is_initialized = true;
    }
}

