<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/grpc/config.proto

namespace Xray\Transport\Internet\Grpc\Encoding;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.transport.internet.grpc.encoding.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string authority = 1;</code>
     */
    protected $authority = '';
    /**
     * Generated from protobuf field <code>string service_name = 2;</code>
     */
    protected $service_name = '';
    /**
     * Generated from protobuf field <code>bool multi_mode = 3;</code>
     */
    protected $multi_mode = false;
    /**
     * Generated from protobuf field <code>int32 idle_timeout = 4;</code>
     */
    protected $idle_timeout = 0;
    /**
     * Generated from protobuf field <code>int32 health_check_timeout = 5;</code>
     */
    protected $health_check_timeout = 0;
    /**
     * Generated from protobuf field <code>bool permit_without_stream = 6;</code>
     */
    protected $permit_without_stream = false;
    /**
     * Generated from protobuf field <code>int32 initial_windows_size = 7;</code>
     */
    protected $initial_windows_size = 0;
    /**
     * Generated from protobuf field <code>string user_agent = 8;</code>
     */
    protected $user_agent = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $authority
     *     @type string $service_name
     *     @type bool $multi_mode
     *     @type int $idle_timeout
     *     @type int $health_check_timeout
     *     @type bool $permit_without_stream
     *     @type int $initial_windows_size
     *     @type string $user_agent
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transport\Internet\Grpc\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string authority = 1;</code>
     * @return string
     */
    public function getAuthority()
    {
        return $this->authority;
    }

    /**
     * Generated from protobuf field <code>string authority = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAuthority($var)
    {
        GPBUtil::checkString($var, True);
        $this->authority = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string service_name = 2;</code>
     * @return string
     */
    public function getServiceName()
    {
        return $this->service_name;
    }

    /**
     * Generated from protobuf field <code>string service_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setServiceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->service_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool multi_mode = 3;</code>
     * @return bool
     */
    public function getMultiMode()
    {
        return $this->multi_mode;
    }

    /**
     * Generated from protobuf field <code>bool multi_mode = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setMultiMode($var)
    {
        GPBUtil::checkBool($var);
        $this->multi_mode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 idle_timeout = 4;</code>
     * @return int
     */
    public function getIdleTimeout()
    {
        return $this->idle_timeout;
    }

    /**
     * Generated from protobuf field <code>int32 idle_timeout = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setIdleTimeout($var)
    {
        GPBUtil::checkInt32($var);
        $this->idle_timeout = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 health_check_timeout = 5;</code>
     * @return int
     */
    public function getHealthCheckTimeout()
    {
        return $this->health_check_timeout;
    }

    /**
     * Generated from protobuf field <code>int32 health_check_timeout = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setHealthCheckTimeout($var)
    {
        GPBUtil::checkInt32($var);
        $this->health_check_timeout = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool permit_without_stream = 6;</code>
     * @return bool
     */
    public function getPermitWithoutStream()
    {
        return $this->permit_without_stream;
    }

    /**
     * Generated from protobuf field <code>bool permit_without_stream = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setPermitWithoutStream($var)
    {
        GPBUtil::checkBool($var);
        $this->permit_without_stream = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 initial_windows_size = 7;</code>
     * @return int
     */
    public function getInitialWindowsSize()
    {
        return $this->initial_windows_size;
    }

    /**
     * Generated from protobuf field <code>int32 initial_windows_size = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setInitialWindowsSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->initial_windows_size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_agent = 8;</code>
     * @return string
     */
    public function getUserAgent()
    {
        return $this->user_agent;
    }

    /**
     * Generated from protobuf field <code>string user_agent = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setUserAgent($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_agent = $var;

        return $this;
    }

}

