<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/headers/tls/config.proto

namespace GPBMetadata\Transport\Internet\Headers\Tls;

use Google\Protobuf\Internal\DescriptorPool;

class Config
{
    public static $is_initialized = false;

    public static function initOnce()
    {
        $pool = DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
            return;
        }
        $pool->internalAddGeneratedFile(
            '
�
+transport/internet/headers/tls/config.proto#xray.transport.internet.headers.tls"
PacketConfigB�
\'com.xray.transport.internet.headers.tlsPZ8github.com/xtls/xray-core/transport/internet/headers/tls�#Xray.Transport.Internet.Headers.Tlsbproto3'
            , true);

        static::$is_initialized = true;
    }
}

