<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/protocol/user.proto

namespace GPBMetadata\Common\Protocol;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Serial\TypedMessage::initOnce();
        $pool->internalAddGeneratedFile(
            '
ó
common/protocol/user.protoxray.common.protocol"W
User
level (
email (	1
account (2 .xray.common.serial.TypedMessageB^
com.xray.common.protocolPZ)github.com/xtls/xray-core/common/protocolªXray.Common.Protocolbproto3'
        , true);

        static::$is_initialized = true;
    }
}

