<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/grpc/encoding/stream.proto

namespace GPBMetadata\Transport\Internet\Grpc\Encoding;

class Stream
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
¶
-transport/internet/grpc/encoding/stream.proto%xray.transport.internet.grpc.encoding"
Hunk
data ("
	MultiHunk
data (2æ
GRPCServicec
Tun+.xray.transport.internet.grpc.encoding.Hunk+.xray.transport.internet.grpc.encoding.Hunk(0r
TunMulti0.xray.transport.internet.grpc.encoding.MultiHunk0.xray.transport.internet.grpc.encoding.MultiHunk(0B<Z:github.com/xtls/xray-core/transport/internet/grpc/encodingbproto3'
        , true);

        static::$is_initialized = true;
    }
}

