<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/http/config.proto

namespace GPBMetadata\Transport\Internet\Http;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Transport\Internet\Headers\Http\Config::initOnce();
        $pool->internalAddGeneratedFile(
            '
í
$transport/internet/http/config.protoxray.transport.internet.http"¦
Config
host (	
path (	
idle_timeout (
health_check_timeout (
method (	<
header (2,.xray.transport.internet.headers.http.HeaderBv
 com.xray.transport.internet.httpPZ1github.com/xtls/xray-core/transport/internet/httpªXray.Transport.Internet.Httpbproto3'
        , true);

        static::$is_initialized = true;
    }
}

