<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/trojan/config.proto

namespace Xray\Proxy\Trojan;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\Internal\RepeatedField;
use GPBMetadata\Proxy\Trojan\Config;
use Xray\Common\Protocol\ServerEndpoint;

/**
 * Generated from protobuf message <code>xray.proxy.trojan.ClientConfig</code>
 */
class ClientConfig extends Message
{
    /**
     * Generated from protobuf field <code>repeated .xray.common.protocol.ServerEndpoint server = 1;</code>
     */
    private $server;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * @type array<ServerEndpoint>|RepeatedField $server
     * }
     */
    public function __construct($data = NULL)
    {
        Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.protocol.ServerEndpoint server = 1;</code>
     * @return RepeatedField
     */
    public function getServer()
    {
        return $this->server;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.protocol.ServerEndpoint server = 1;</code>
     * @param array<ServerEndpoint>|RepeatedField $var
     * @return $this
     */
    public function setServer($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, ServerEndpoint::class);
        $this->server = $arr;

        return $this;
    }

}

