<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/trojan/config.proto

namespace Xray\Proxy\Trojan;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\Internal\RepeatedField;
use GPBMetadata\Proxy\Trojan\Config;
use Xray\Common\Protocol\User;

/**
 * Generated from protobuf message <code>xray.proxy.trojan.ServerConfig</code>
 */
class ServerConfig extends Message
{
    /**
     * Generated from protobuf field <code>repeated .xray.common.protocol.User users = 1;</code>
     */
    private $users;
    /**
     * Generated from protobuf field <code>repeated .xray.proxy.trojan.Fallback fallbacks = 2;</code>
     */
    private $fallbacks;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * @type array<User>|RepeatedField $users
     * @type array<Fallback>|RepeatedField $fallbacks
     * }
     */
    public function __construct($data = NULL)
    {
        Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.protocol.User users = 1;</code>
     * @return RepeatedField
     */
    public function getUsers()
    {
        return $this->users;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.protocol.User users = 1;</code>
     * @param array<User>|RepeatedField $var
     * @return $this
     */
    public function setUsers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, User::class);
        $this->users = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.proxy.trojan.Fallback fallbacks = 2;</code>
     * @return RepeatedField
     */
    public function getFallbacks()
    {
        return $this->fallbacks;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.proxy.trojan.Fallback fallbacks = 2;</code>
     * @param array<Fallback>|RepeatedField $var
     * @return $this
     */
    public function setFallbacks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Fallback::class);
        $this->fallbacks = $arr;

        return $this;
    }

}

