<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/trojan/config.proto

namespace Xray\Proxy\Trojan;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.proxy.trojan.ServerConfig</code>
 */
class ServerConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .xray.common.protocol.User users = 1;</code>
     */
    private $users;
    /**
     * Generated from protobuf field <code>repeated .xray.proxy.trojan.Fallback fallbacks = 2;</code>
     */
    private $fallbacks;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Xray\Common\Protocol\User>|\Google\Protobuf\Internal\RepeatedField $users
     *     @type array<\Xray\Proxy\Trojan\Fallback>|\Google\Protobuf\Internal\RepeatedField $fallbacks
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proxy\Trojan\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.protocol.User users = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUsers()
    {
        return $this->users;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.protocol.User users = 1;</code>
     * @param array<\Xray\Common\Protocol\User>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUsers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xray\Common\Protocol\User::class);
        $this->users = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.proxy.trojan.Fallback fallbacks = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFallbacks()
    {
        return $this->fallbacks;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.proxy.trojan.Fallback fallbacks = 2;</code>
     * @param array<\Xray\Proxy\Trojan\Fallback>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFallbacks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xray\Proxy\Trojan\Fallback::class);
        $this->fallbacks = $arr;

        return $this;
    }

}

