<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/headers/wechat/config.proto

namespace GPBMetadata\Transport\Internet\Headers\Wechat;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
†
.transport/internet/headers/wechat/config.proto&xray.transport.internet.headers.wechat"
VideoConfigB”
*com.xray.transport.internet.headers.wechatPZ;github.com/xtls/xray-core/transport/internet/headers/wechatª&Xray.Transport.Internet.Headers.Wechatbproto3'
        , true);

        static::$is_initialized = true;
    }
}

