<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/stats/config.proto

namespace GPBMetadata\App\Stats;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Ø
app/stats/config.protoxray.app.stats"
Config"N
ChannelConfig
Blocking (
SubscriberLimit (

BufferSize (BL
com.xray.app.statsPZ#github.com/xtls/xray-core/app/statsªXray.App.Statsbproto3'
        , true);

        static::$is_initialized = true;
    }
}

