<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/headers/wireguard/config.proto

namespace Xray\Transport\Internet\Headers\Wireguard;

use Google\Protobuf\Internal\Message;
use GPBMetadata\Transport\Internet\Headers\Wireguard\Config;

/**
 * Generated from protobuf message <code>xray.transport.internet.headers.wireguard.WireguardConfig</code>
 */
class WireguardConfig extends Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL)
    {
        Config::initOnce();
        parent::__construct($data);
    }

}

