<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/wireguard/config.proto

namespace Xray\Proxy\Wireguard;

if (false) {
    /**
     * This class is deprecated. Use Xray\Proxy\Wireguard\DeviceConfig\DomainStrategy instead.
     * @deprecated
     */
    class DeviceConfig_DomainStrategy
    {
    }
}
class_exists(DeviceConfig\DomainStrategy::class);
@trigger_error('Xray\Proxy\Wireguard\DeviceConfig_DomainStrategy is deprecated and will be removed in the next major release. Use Xray\Proxy\Wireguard\DeviceConfig\DomainStrategy instead', E_USER_DEPRECATED);

