<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/wireguard/config.proto

namespace Xray\Proxy\Wireguard;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.proxy.wireguard.PeerConfig</code>
 */
class PeerConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string public_key = 1;</code>
     */
    protected $public_key = '';
    /**
     * Generated from protobuf field <code>string pre_shared_key = 2;</code>
     */
    protected $pre_shared_key = '';
    /**
     * Generated from protobuf field <code>string endpoint = 3;</code>
     */
    protected $endpoint = '';
    /**
     * Generated from protobuf field <code>uint32 keep_alive = 4;</code>
     */
    protected $keep_alive = 0;
    /**
     * Generated from protobuf field <code>repeated string allowed_ips = 5;</code>
     */
    private $allowed_ips;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $public_key
     *     @type string $pre_shared_key
     *     @type string $endpoint
     *     @type int $keep_alive
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $allowed_ips
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proxy\Wireguard\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string public_key = 1;</code>
     * @return string
     */
    public function getPublicKey()
    {
        return $this->public_key;
    }

    /**
     * Generated from protobuf field <code>string public_key = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPublicKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->public_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string pre_shared_key = 2;</code>
     * @return string
     */
    public function getPreSharedKey()
    {
        return $this->pre_shared_key;
    }

    /**
     * Generated from protobuf field <code>string pre_shared_key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPreSharedKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->pre_shared_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string endpoint = 3;</code>
     * @return string
     */
    public function getEndpoint()
    {
        return $this->endpoint;
    }

    /**
     * Generated from protobuf field <code>string endpoint = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setEndpoint($var)
    {
        GPBUtil::checkString($var, True);
        $this->endpoint = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 keep_alive = 4;</code>
     * @return int
     */
    public function getKeepAlive()
    {
        return $this->keep_alive;
    }

    /**
     * Generated from protobuf field <code>uint32 keep_alive = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setKeepAlive($var)
    {
        GPBUtil::checkUint32($var);
        $this->keep_alive = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string allowed_ips = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAllowedIps()
    {
        return $this->allowed_ips;
    }

    /**
     * Generated from protobuf field <code>repeated string allowed_ips = 5;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAllowedIps($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->allowed_ips = $arr;

        return $this;
    }

}

