<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/headers/utp/config.proto

namespace GPBMetadata\Transport\Internet\Headers\Utp;

use Google\Protobuf\Internal\DescriptorPool;

class Config
{
    public static $is_initialized = false;

    public static function initOnce()
    {
        $pool = DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
            return;
        }
        $pool->internalAddGeneratedFile(
            '
�
+transport/internet/headers/utp/config.proto#xray.transport.internet.headers.utp"
Config
version (
B�
\'com.xray.transport.internet.headers.utpPZ8github.com/xtls/xray-core/transport/internet/headers/utp�#Xray.Transport.Internet.Headers.Utpbproto3'
            , true);

        static::$is_initialized = true;
    }
}

