<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/commander/config.proto

namespace Xray\App\Commander;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\Internal\RepeatedField;
use Xray\Common\Serial\TypedMessage;

/**
 * Config is the settings for Commander.
 *
 * Generated from protobuf message <code>xray.app.commander.Config</code>
 */
class Config extends Message
{
    /**
     * Tag of the outbound handler that handles grpc connections.
     *
     * Generated from protobuf field <code>string tag = 1;</code>
     */
    protected $tag = '';
    /**
     * Network address of commander grpc service.
     *
     * Generated from protobuf field <code>string listen = 3;</code>
     */
    protected $listen = '';
    /**
     * Services that supported by this server. All services must implement Service
     * interface.
     *
     * Generated from protobuf field <code>repeated .xray.common.serial.TypedMessage service = 2;</code>
     */
    private $service;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * @type string $tag
     *           Tag of the outbound handler that handles grpc connections.
     * @type string $listen
     *           Network address of commander grpc service.
     * @type array<TypedMessage>|RepeatedField $service
     *           Services that supported by this server. All services must implement Service
     *           interface.
     * }
     */
    public function __construct($data = NULL)
    {
        \GPBMetadata\App\Commander\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Tag of the outbound handler that handles grpc connections.
     *
     * Generated from protobuf field <code>string tag = 1;</code>
     * @return string
     */
    public function getTag()
    {
        return $this->tag;
    }

    /**
     * Tag of the outbound handler that handles grpc connections.
     *
     * Generated from protobuf field <code>string tag = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTag($var)
    {
        GPBUtil::checkString($var, True);
        $this->tag = $var;

        return $this;
    }

    /**
     * Network address of commander grpc service.
     *
     * Generated from protobuf field <code>string listen = 3;</code>
     * @return string
     */
    public function getListen()
    {
        return $this->listen;
    }

    /**
     * Network address of commander grpc service.
     *
     * Generated from protobuf field <code>string listen = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setListen($var)
    {
        GPBUtil::checkString($var, True);
        $this->listen = $var;

        return $this;
    }

    /**
     * Services that supported by this server. All services must implement Service
     * interface.
     *
     * Generated from protobuf field <code>repeated .xray.common.serial.TypedMessage service = 2;</code>
     * @return RepeatedField
     */
    public function getService()
    {
        return $this->service;
    }

    /**
     * Services that supported by this server. All services must implement Service
     * interface.
     *
     * Generated from protobuf field <code>repeated .xray.common.serial.TypedMessage service = 2;</code>
     * @param array<TypedMessage>|RepeatedField $var
     * @return $this
     */
    public function setService($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, TypedMessage::class);
        $this->service = $arr;

        return $this;
    }

}

