<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/protocol/headers.proto

namespace Xray\Common\Protocol;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use GPBMetadata\Common\Protocol\Headers;

/**
 * Generated from protobuf message <code>xray.common.protocol.SecurityConfig</code>
 */
class SecurityConfig extends Message
{
    /**
     * Generated from protobuf field <code>.xray.common.protocol.SecurityType type = 1;</code>
     */
    protected $type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * @type int $type
     * }
     */
    public function __construct($data = NULL)
    {
        Headers::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.xray.common.protocol.SecurityType type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.xray.common.protocol.SecurityType type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, SecurityType::class);
        $this->type = $var;

        return $this;
    }

}

