<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/protocol/server_spec.proto

namespace Xray\Common\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\Internal\RepeatedField;
use GPBMetadata\Common\Protocol\ServerSpec;
use Xray\Common\Net\IPOrDomain;

/**
 * Generated from protobuf message <code>xray.common.protocol.ServerEndpoint</code>
 */
class ServerEndpoint extends Message
{
    /**
     * Generated from protobuf field <code>.xray.common.net.IPOrDomain address = 1;</code>
     */
    protected $address = null;
    /**
     * Generated from protobuf field <code>uint32 port = 2;</code>
     */
    protected $port = 0;
    /**
     * Generated from protobuf field <code>repeated .xray.common.protocol.User user = 3;</code>
     */
    private $user;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * @type IPOrDomain $address
     * @type int $port
     * @type array<User>|RepeatedField $user
     * }
     */
    public function __construct($data = NULL)
    {
        ServerSpec::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.xray.common.net.IPOrDomain address = 1;</code>
     * @return IPOrDomain|null
     */
    public function getAddress()
    {
        return $this->address;
    }

    public function hasAddress()
    {
        return isset($this->address);
    }

    public function clearAddress()
    {
        unset($this->address);
    }

    /**
     * Generated from protobuf field <code>.xray.common.net.IPOrDomain address = 1;</code>
     * @param IPOrDomain $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkMessage($var, IPOrDomain::class);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 port = 2;</code>
     * @return int
     */
    public function getPort()
    {
        return $this->port;
    }

    /**
     * Generated from protobuf field <code>uint32 port = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPort($var)
    {
        GPBUtil::checkUint32($var);
        $this->port = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.protocol.User user = 3;</code>
     * @return RepeatedField
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.protocol.User user = 3;</code>
     * @param array<User>|RepeatedField $var
     * @return $this
     */
    public function setUser($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, User::class);
        $this->user = $arr;

        return $this;
    }

}

