<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/blackhole/config.proto

namespace Xray\Proxy\Blackhole;

use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>xray.proxy.blackhole.NoneResponse</code>
 */
class NoneResponse extends Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL)
    {
        \GPBMetadata\Proxy\Blackhole\Config::initOnce();
        parent::__construct($data);
    }

}

