<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/serial/typed_message.proto

namespace GPBMetadata\Common\Serial;

use Google\Protobuf\Internal\DescriptorPool;

class TypedMessage
{
    public static $is_initialized = false;

    public static function initOnce()
    {
        $pool = DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
            return;
        }
        $pool->internalAddGeneratedFile(
            '
�
!common/serial/typed_message.protoxray.common.serial"+
TypedMessage
type (	
value (BX
com.xray.common.serialPZ\'github.com/xtls/xray-core/common/serial�Xray.Common.Serialbproto3'
            , true);

        static::$is_initialized = true;
    }
}

