<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/serial/typed_message.proto

namespace GPBMetadata\Common\Serial;

class TypedMessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Æ
!common/serial/typed_message.protoxray.common.serial"+
TypedMessage
type (	
value (BX
com.xray.common.serialPZ\'github.com/xtls/xray-core/common/serialªXray.Common.Serialbproto3'
        , true);

        static::$is_initialized = true;
    }
}

