<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/headers/tls/config.proto

namespace Xray\Transport\Internet\Headers\Tls;

use Google\Protobuf\Internal\Message;
use GPBMetadata\Transport\Internet\Headers\Tls\Config;

/**
 * Generated from protobuf message <code>xray.transport.internet.headers.tls.PacketConfig</code>
 */
class PacketConfig extends Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL)
    {
        Config::initOnce();
        parent::__construct($data);
    }

}

