<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/freedom/config.proto

namespace Xray\Proxy\Freedom;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.proxy.freedom.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.xray.proxy.freedom.Config.DomainStrategy domain_strategy = 1;</code>
     */
    protected $domain_strategy = 0;
    /**
     * Generated from protobuf field <code>.xray.proxy.freedom.DestinationOverride destination_override = 3;</code>
     */
    protected $destination_override = null;
    /**
     * Generated from protobuf field <code>uint32 user_level = 4;</code>
     */
    protected $user_level = 0;
    /**
     * Generated from protobuf field <code>.xray.proxy.freedom.Fragment fragment = 5;</code>
     */
    protected $fragment = null;
    /**
     * Generated from protobuf field <code>uint32 proxy_protocol = 6;</code>
     */
    protected $proxy_protocol = 0;
    /**
     * Generated from protobuf field <code>repeated .xray.proxy.freedom.Noise noises = 7;</code>
     */
    private $noises;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $domain_strategy
     *     @type \Xray\Proxy\Freedom\DestinationOverride $destination_override
     *     @type int $user_level
     *     @type \Xray\Proxy\Freedom\Fragment $fragment
     *     @type int $proxy_protocol
     *     @type array<\Xray\Proxy\Freedom\Noise>|\Google\Protobuf\Internal\RepeatedField $noises
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proxy\Freedom\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.xray.proxy.freedom.Config.DomainStrategy domain_strategy = 1;</code>
     * @return int
     */
    public function getDomainStrategy()
    {
        return $this->domain_strategy;
    }

    /**
     * Generated from protobuf field <code>.xray.proxy.freedom.Config.DomainStrategy domain_strategy = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setDomainStrategy($var)
    {
        GPBUtil::checkEnum($var, \Xray\Proxy\Freedom\Config\DomainStrategy::class);
        $this->domain_strategy = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.proxy.freedom.DestinationOverride destination_override = 3;</code>
     * @return \Xray\Proxy\Freedom\DestinationOverride|null
     */
    public function getDestinationOverride()
    {
        return $this->destination_override;
    }

    public function hasDestinationOverride()
    {
        return isset($this->destination_override);
    }

    public function clearDestinationOverride()
    {
        unset($this->destination_override);
    }

    /**
     * Generated from protobuf field <code>.xray.proxy.freedom.DestinationOverride destination_override = 3;</code>
     * @param \Xray\Proxy\Freedom\DestinationOverride $var
     * @return $this
     */
    public function setDestinationOverride($var)
    {
        GPBUtil::checkMessage($var, \Xray\Proxy\Freedom\DestinationOverride::class);
        $this->destination_override = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 user_level = 4;</code>
     * @return int
     */
    public function getUserLevel()
    {
        return $this->user_level;
    }

    /**
     * Generated from protobuf field <code>uint32 user_level = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setUserLevel($var)
    {
        GPBUtil::checkUint32($var);
        $this->user_level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.proxy.freedom.Fragment fragment = 5;</code>
     * @return \Xray\Proxy\Freedom\Fragment|null
     */
    public function getFragment()
    {
        return $this->fragment;
    }

    public function hasFragment()
    {
        return isset($this->fragment);
    }

    public function clearFragment()
    {
        unset($this->fragment);
    }

    /**
     * Generated from protobuf field <code>.xray.proxy.freedom.Fragment fragment = 5;</code>
     * @param \Xray\Proxy\Freedom\Fragment $var
     * @return $this
     */
    public function setFragment($var)
    {
        GPBUtil::checkMessage($var, \Xray\Proxy\Freedom\Fragment::class);
        $this->fragment = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 proxy_protocol = 6;</code>
     * @return int
     */
    public function getProxyProtocol()
    {
        return $this->proxy_protocol;
    }

    /**
     * Generated from protobuf field <code>uint32 proxy_protocol = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setProxyProtocol($var)
    {
        GPBUtil::checkUint32($var);
        $this->proxy_protocol = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.proxy.freedom.Noise noises = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNoises()
    {
        return $this->noises;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.proxy.freedom.Noise noises = 7;</code>
     * @param array<\Xray\Proxy\Freedom\Noise>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNoises($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xray\Proxy\Freedom\Noise::class);
        $this->noises = $arr;

        return $this;
    }

}

