<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/freedom/config.proto

namespace Xray\Proxy\Freedom;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.proxy.freedom.DestinationOverride</code>
 */
class DestinationOverride extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.xray.common.protocol.ServerEndpoint server = 1;</code>
     */
    protected $server = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Xray\Common\Protocol\ServerEndpoint $server
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proxy\Freedom\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.xray.common.protocol.ServerEndpoint server = 1;</code>
     * @return \Xray\Common\Protocol\ServerEndpoint|null
     */
    public function getServer()
    {
        return $this->server;
    }

    public function hasServer()
    {
        return isset($this->server);
    }

    public function clearServer()
    {
        unset($this->server);
    }

    /**
     * Generated from protobuf field <code>.xray.common.protocol.ServerEndpoint server = 1;</code>
     * @param \Xray\Common\Protocol\ServerEndpoint $var
     * @return $this
     */
    public function setServer($var)
    {
        GPBUtil::checkMessage($var, \Xray\Common\Protocol\ServerEndpoint::class);
        $this->server = $var;

        return $this;
    }

}

