<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/tcp/config.proto

namespace GPBMetadata\Transport\Internet\Tcp;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Serial\TypedMessage::initOnce();
        $pool->internalAddGeneratedFile(
            '
©
#transport/internet/tcp/config.protoxray.transport.internet.tcp"h
Config9
header_settings (2 .xray.common.serial.TypedMessage
accept_proxy_protocol (JBs
com.xray.transport.internet.tcpPZ0github.com/xtls/xray-core/transport/internet/tcpªXray.Transport.Internet.Tcpbproto3'
        , true);

        static::$is_initialized = true;
    }
}

