<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/tcp/config.proto

namespace GPBMetadata\Transport\Internet\Tcp;

use Google\Protobuf\Internal\DescriptorPool;
use GPBMetadata\Common\Serial\TypedMessage;

class Config
{
    public static $is_initialized = false;

    public static function initOnce()
    {
        $pool = DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
            return;
        }
        TypedMessage::initOnce();
        $pool->internalAddGeneratedFile(
            '
�
#transport/internet/tcp/config.protoxray.transport.internet.tcp"h
Config9
header_settings (2 .xray.common.serial.TypedMessage
accept_proxy_protocol (JBs
com.xray.transport.internet.tcpPZ0github.com/xtls/xray-core/transport/internet/tcp�Xray.Transport.Internet.Tcpbproto3'
            , true);

        static::$is_initialized = true;
    }
}

