<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/observatory/config.proto

namespace Xray\Core\App\Observatory;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\Internal\RepeatedField;

/**
 * Generated from protobuf message <code>xray.core.app.observatory.ObservationResult</code>
 */
class ObservationResult extends Message
{
    /**
     * Generated from protobuf field <code>repeated .xray.core.app.observatory.OutboundStatus status = 1;</code>
     */
    private $status;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * @type array<OutboundStatus>|RepeatedField $status
     * }
     */
    public function __construct($data = NULL)
    {
        \GPBMetadata\App\Observatory\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .xray.core.app.observatory.OutboundStatus status = 1;</code>
     * @return RepeatedField
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.core.app.observatory.OutboundStatus status = 1;</code>
     * @param array<OutboundStatus>|RepeatedField $var
     * @return $this
     */
    public function setStatus($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, OutboundStatus::class);
        $this->status = $arr;

        return $this;
    }

}

