<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/proxyman/config.proto

namespace Xray\App\Proxyman;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.app.proxyman.AllocationStrategy</code>
 */
class AllocationStrategy extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.xray.app.proxyman.AllocationStrategy.Type type = 1;</code>
     */
    protected $type = 0;
    /**
     * Number of handlers (ports) running in parallel.
     * Default value is 3 if unset.
     *
     * Generated from protobuf field <code>.xray.app.proxyman.AllocationStrategy.AllocationStrategyConcurrency concurrency = 2;</code>
     */
    protected $concurrency = null;
    /**
     * Number of minutes before a handler is regenerated.
     * Default value is 5 if unset.
     *
     * Generated from protobuf field <code>.xray.app.proxyman.AllocationStrategy.AllocationStrategyRefresh refresh = 3;</code>
     */
    protected $refresh = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *     @type \Xray\App\Proxyman\AllocationStrategy\AllocationStrategyConcurrency $concurrency
     *           Number of handlers (ports) running in parallel.
     *           Default value is 3 if unset.
     *     @type \Xray\App\Proxyman\AllocationStrategy\AllocationStrategyRefresh $refresh
     *           Number of minutes before a handler is regenerated.
     *           Default value is 5 if unset.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Proxyman\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.xray.app.proxyman.AllocationStrategy.Type type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.xray.app.proxyman.AllocationStrategy.Type type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Xray\App\Proxyman\AllocationStrategy\Type::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Number of handlers (ports) running in parallel.
     * Default value is 3 if unset.
     *
     * Generated from protobuf field <code>.xray.app.proxyman.AllocationStrategy.AllocationStrategyConcurrency concurrency = 2;</code>
     * @return \Xray\App\Proxyman\AllocationStrategy\AllocationStrategyConcurrency|null
     */
    public function getConcurrency()
    {
        return $this->concurrency;
    }

    public function hasConcurrency()
    {
        return isset($this->concurrency);
    }

    public function clearConcurrency()
    {
        unset($this->concurrency);
    }

    /**
     * Number of handlers (ports) running in parallel.
     * Default value is 3 if unset.
     *
     * Generated from protobuf field <code>.xray.app.proxyman.AllocationStrategy.AllocationStrategyConcurrency concurrency = 2;</code>
     * @param \Xray\App\Proxyman\AllocationStrategy\AllocationStrategyConcurrency $var
     * @return $this
     */
    public function setConcurrency($var)
    {
        GPBUtil::checkMessage($var, \Xray\App\Proxyman\AllocationStrategy\AllocationStrategyConcurrency::class);
        $this->concurrency = $var;

        return $this;
    }

    /**
     * Number of minutes before a handler is regenerated.
     * Default value is 5 if unset.
     *
     * Generated from protobuf field <code>.xray.app.proxyman.AllocationStrategy.AllocationStrategyRefresh refresh = 3;</code>
     * @return \Xray\App\Proxyman\AllocationStrategy\AllocationStrategyRefresh|null
     */
    public function getRefresh()
    {
        return $this->refresh;
    }

    public function hasRefresh()
    {
        return isset($this->refresh);
    }

    public function clearRefresh()
    {
        unset($this->refresh);
    }

    /**
     * Number of minutes before a handler is regenerated.
     * Default value is 5 if unset.
     *
     * Generated from protobuf field <code>.xray.app.proxyman.AllocationStrategy.AllocationStrategyRefresh refresh = 3;</code>
     * @param \Xray\App\Proxyman\AllocationStrategy\AllocationStrategyRefresh $var
     * @return $this
     */
    public function setRefresh($var)
    {
        GPBUtil::checkMessage($var, \Xray\App\Proxyman\AllocationStrategy\AllocationStrategyRefresh::class);
        $this->refresh = $var;

        return $this;
    }

}

