<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/proxyman/config.proto

namespace Xray\App\Proxyman;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use GPBMetadata\App\Proxyman\Config;
use Xray\Common\Serial\TypedMessage;

/**
 * Generated from protobuf message <code>xray.app.proxyman.InboundHandlerConfig</code>
 */
class InboundHandlerConfig extends Message
{
    /**
     * Generated from protobuf field <code>string tag = 1;</code>
     */
    protected $tag = '';
    /**
     * Generated from protobuf field <code>.xray.common.serial.TypedMessage receiver_settings = 2;</code>
     */
    protected $receiver_settings = null;
    /**
     * Generated from protobuf field <code>.xray.common.serial.TypedMessage proxy_settings = 3;</code>
     */
    protected $proxy_settings = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * @type string $tag
     * @type TypedMessage $receiver_settings
     * @type TypedMessage $proxy_settings
     * }
     */
    public function __construct($data = NULL)
    {
        Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string tag = 1;</code>
     * @return string
     */
    public function getTag()
    {
        return $this->tag;
    }

    /**
     * Generated from protobuf field <code>string tag = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTag($var)
    {
        GPBUtil::checkString($var, True);
        $this->tag = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.common.serial.TypedMessage receiver_settings = 2;</code>
     * @return TypedMessage|null
     */
    public function getReceiverSettings()
    {
        return $this->receiver_settings;
    }

    public function hasReceiverSettings()
    {
        return isset($this->receiver_settings);
    }

    public function clearReceiverSettings()
    {
        unset($this->receiver_settings);
    }

    /**
     * Generated from protobuf field <code>.xray.common.serial.TypedMessage receiver_settings = 2;</code>
     * @param TypedMessage $var
     * @return $this
     */
    public function setReceiverSettings($var)
    {
        GPBUtil::checkMessage($var, TypedMessage::class);
        $this->receiver_settings = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.common.serial.TypedMessage proxy_settings = 3;</code>
     * @return TypedMessage|null
     */
    public function getProxySettings()
    {
        return $this->proxy_settings;
    }

    public function hasProxySettings()
    {
        return isset($this->proxy_settings);
    }

    public function clearProxySettings()
    {
        unset($this->proxy_settings);
    }

    /**
     * Generated from protobuf field <code>.xray.common.serial.TypedMessage proxy_settings = 3;</code>
     * @param TypedMessage $var
     * @return $this
     */
    public function setProxySettings($var)
    {
        GPBUtil::checkMessage($var, TypedMessage::class);
        $this->proxy_settings = $var;

        return $this;
    }

}

