<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/proxyman/config.proto

namespace Xray\App\Proxyman;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.app.proxyman.MultiplexingConfig</code>
 */
class MultiplexingConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Whether or not Mux is enabled.
     *
     * Generated from protobuf field <code>bool enabled = 1;</code>
     */
    protected $enabled = false;
    /**
     * Max number of concurrent connections that one Mux connection can handle.
     *
     * Generated from protobuf field <code>int32 concurrency = 2;</code>
     */
    protected $concurrency = 0;
    /**
     * Transport XUDP in another Mux.
     *
     * Generated from protobuf field <code>int32 xudpConcurrency = 3;</code>
     */
    protected $xudpConcurrency = 0;
    /**
     * "reject" (default), "allow" or "skip".
     *
     * Generated from protobuf field <code>string xudpProxyUDP443 = 4;</code>
     */
    protected $xudpProxyUDP443 = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $enabled
     *           Whether or not Mux is enabled.
     *     @type int $concurrency
     *           Max number of concurrent connections that one Mux connection can handle.
     *     @type int $xudpConcurrency
     *           Transport XUDP in another Mux.
     *     @type string $xudpProxyUDP443
     *           "reject" (default), "allow" or "skip".
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Proxyman\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Whether or not Mux is enabled.
     *
     * Generated from protobuf field <code>bool enabled = 1;</code>
     * @return bool
     */
    public function getEnabled()
    {
        return $this->enabled;
    }

    /**
     * Whether or not Mux is enabled.
     *
     * Generated from protobuf field <code>bool enabled = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setEnabled($var)
    {
        GPBUtil::checkBool($var);
        $this->enabled = $var;

        return $this;
    }

    /**
     * Max number of concurrent connections that one Mux connection can handle.
     *
     * Generated from protobuf field <code>int32 concurrency = 2;</code>
     * @return int
     */
    public function getConcurrency()
    {
        return $this->concurrency;
    }

    /**
     * Max number of concurrent connections that one Mux connection can handle.
     *
     * Generated from protobuf field <code>int32 concurrency = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setConcurrency($var)
    {
        GPBUtil::checkInt32($var);
        $this->concurrency = $var;

        return $this;
    }

    /**
     * Transport XUDP in another Mux.
     *
     * Generated from protobuf field <code>int32 xudpConcurrency = 3;</code>
     * @return int
     */
    public function getXudpConcurrency()
    {
        return $this->xudpConcurrency;
    }

    /**
     * Transport XUDP in another Mux.
     *
     * Generated from protobuf field <code>int32 xudpConcurrency = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setXudpConcurrency($var)
    {
        GPBUtil::checkInt32($var);
        $this->xudpConcurrency = $var;

        return $this;
    }

    /**
     * "reject" (default), "allow" or "skip".
     *
     * Generated from protobuf field <code>string xudpProxyUDP443 = 4;</code>
     * @return string
     */
    public function getXudpProxyUDP443()
    {
        return $this->xudpProxyUDP443;
    }

    /**
     * "reject" (default), "allow" or "skip".
     *
     * Generated from protobuf field <code>string xudpProxyUDP443 = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setXudpProxyUDP443($var)
    {
        GPBUtil::checkString($var, True);
        $this->xudpProxyUDP443 = $var;

        return $this;
    }

}

