<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/proxyman/config.proto

namespace Xray\App\Proxyman;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.app.proxyman.SenderConfig</code>
 */
class SenderConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Send traffic through the given IP. Only IP is allowed.
     *
     * Generated from protobuf field <code>.xray.common.net.IPOrDomain via = 1;</code>
     */
    protected $via = null;
    /**
     * Generated from protobuf field <code>.xray.transport.internet.StreamConfig stream_settings = 2;</code>
     */
    protected $stream_settings = null;
    /**
     * Generated from protobuf field <code>.xray.transport.internet.ProxyConfig proxy_settings = 3;</code>
     */
    protected $proxy_settings = null;
    /**
     * Generated from protobuf field <code>.xray.app.proxyman.MultiplexingConfig multiplex_settings = 4;</code>
     */
    protected $multiplex_settings = null;
    /**
     * Generated from protobuf field <code>string via_cidr = 5;</code>
     */
    protected $via_cidr = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Xray\Common\Net\IPOrDomain $via
     *           Send traffic through the given IP. Only IP is allowed.
     *     @type \Xray\Transport\Internet\StreamConfig $stream_settings
     *     @type \Xray\Transport\Internet\ProxyConfig $proxy_settings
     *     @type \Xray\App\Proxyman\MultiplexingConfig $multiplex_settings
     *     @type string $via_cidr
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Proxyman\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Send traffic through the given IP. Only IP is allowed.
     *
     * Generated from protobuf field <code>.xray.common.net.IPOrDomain via = 1;</code>
     * @return \Xray\Common\Net\IPOrDomain|null
     */
    public function getVia()
    {
        return $this->via;
    }

    public function hasVia()
    {
        return isset($this->via);
    }

    public function clearVia()
    {
        unset($this->via);
    }

    /**
     * Send traffic through the given IP. Only IP is allowed.
     *
     * Generated from protobuf field <code>.xray.common.net.IPOrDomain via = 1;</code>
     * @param \Xray\Common\Net\IPOrDomain $var
     * @return $this
     */
    public function setVia($var)
    {
        GPBUtil::checkMessage($var, \Xray\Common\Net\IPOrDomain::class);
        $this->via = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.StreamConfig stream_settings = 2;</code>
     * @return \Xray\Transport\Internet\StreamConfig|null
     */
    public function getStreamSettings()
    {
        return $this->stream_settings;
    }

    public function hasStreamSettings()
    {
        return isset($this->stream_settings);
    }

    public function clearStreamSettings()
    {
        unset($this->stream_settings);
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.StreamConfig stream_settings = 2;</code>
     * @param \Xray\Transport\Internet\StreamConfig $var
     * @return $this
     */
    public function setStreamSettings($var)
    {
        GPBUtil::checkMessage($var, \Xray\Transport\Internet\StreamConfig::class);
        $this->stream_settings = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.ProxyConfig proxy_settings = 3;</code>
     * @return \Xray\Transport\Internet\ProxyConfig|null
     */
    public function getProxySettings()
    {
        return $this->proxy_settings;
    }

    public function hasProxySettings()
    {
        return isset($this->proxy_settings);
    }

    public function clearProxySettings()
    {
        unset($this->proxy_settings);
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.ProxyConfig proxy_settings = 3;</code>
     * @param \Xray\Transport\Internet\ProxyConfig $var
     * @return $this
     */
    public function setProxySettings($var)
    {
        GPBUtil::checkMessage($var, \Xray\Transport\Internet\ProxyConfig::class);
        $this->proxy_settings = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.app.proxyman.MultiplexingConfig multiplex_settings = 4;</code>
     * @return \Xray\App\Proxyman\MultiplexingConfig|null
     */
    public function getMultiplexSettings()
    {
        return $this->multiplex_settings;
    }

    public function hasMultiplexSettings()
    {
        return isset($this->multiplex_settings);
    }

    public function clearMultiplexSettings()
    {
        unset($this->multiplex_settings);
    }

    /**
     * Generated from protobuf field <code>.xray.app.proxyman.MultiplexingConfig multiplex_settings = 4;</code>
     * @param \Xray\App\Proxyman\MultiplexingConfig $var
     * @return $this
     */
    public function setMultiplexSettings($var)
    {
        GPBUtil::checkMessage($var, \Xray\App\Proxyman\MultiplexingConfig::class);
        $this->multiplex_settings = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string via_cidr = 5;</code>
     * @return string
     */
    public function getViaCidr()
    {
        return $this->via_cidr;
    }

    /**
     * Generated from protobuf field <code>string via_cidr = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setViaCidr($var)
    {
        GPBUtil::checkString($var, True);
        $this->via_cidr = $var;

        return $this;
    }

}

