<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/proxyman/config.proto

namespace Xray\App\Proxyman;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use GPBMetadata\App\Proxyman\Config;
use Xray\Common\Net\IPOrDomain;
use Xray\Transport\Internet\ProxyConfig;
use Xray\Transport\Internet\StreamConfig;

/**
 * Generated from protobuf message <code>xray.app.proxyman.SenderConfig</code>
 */
class SenderConfig extends Message
{
    /**
     * Send traffic through the given IP. Only IP is allowed.
     *
     * Generated from protobuf field <code>.xray.common.net.IPOrDomain via = 1;</code>
     */
    protected $via = null;
    /**
     * Generated from protobuf field <code>.xray.transport.internet.StreamConfig stream_settings = 2;</code>
     */
    protected $stream_settings = null;
    /**
     * Generated from protobuf field <code>.xray.transport.internet.ProxyConfig proxy_settings = 3;</code>
     */
    protected $proxy_settings = null;
    /**
     * Generated from protobuf field <code>.xray.app.proxyman.MultiplexingConfig multiplex_settings = 4;</code>
     */
    protected $multiplex_settings = null;
    /**
     * Generated from protobuf field <code>string via_cidr = 5;</code>
     */
    protected $via_cidr = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * @type IPOrDomain $via
     *           Send traffic through the given IP. Only IP is allowed.
     * @type StreamConfig $stream_settings
     * @type ProxyConfig $proxy_settings
     * @type MultiplexingConfig $multiplex_settings
     * @type string $via_cidr
     * }
     */
    public function __construct($data = NULL)
    {
        Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Send traffic through the given IP. Only IP is allowed.
     *
     * Generated from protobuf field <code>.xray.common.net.IPOrDomain via = 1;</code>
     * @return IPOrDomain|null
     */
    public function getVia()
    {
        return $this->via;
    }

    public function hasVia()
    {
        return isset($this->via);
    }

    public function clearVia()
    {
        unset($this->via);
    }

    /**
     * Send traffic through the given IP. Only IP is allowed.
     *
     * Generated from protobuf field <code>.xray.common.net.IPOrDomain via = 1;</code>
     * @param IPOrDomain $var
     * @return $this
     */
    public function setVia($var)
    {
        GPBUtil::checkMessage($var, IPOrDomain::class);
        $this->via = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.StreamConfig stream_settings = 2;</code>
     * @return StreamConfig|null
     */
    public function getStreamSettings()
    {
        return $this->stream_settings;
    }

    public function hasStreamSettings()
    {
        return isset($this->stream_settings);
    }

    public function clearStreamSettings()
    {
        unset($this->stream_settings);
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.StreamConfig stream_settings = 2;</code>
     * @param StreamConfig $var
     * @return $this
     */
    public function setStreamSettings($var)
    {
        GPBUtil::checkMessage($var, StreamConfig::class);
        $this->stream_settings = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.ProxyConfig proxy_settings = 3;</code>
     * @return ProxyConfig|null
     */
    public function getProxySettings()
    {
        return $this->proxy_settings;
    }

    public function hasProxySettings()
    {
        return isset($this->proxy_settings);
    }

    public function clearProxySettings()
    {
        unset($this->proxy_settings);
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.ProxyConfig proxy_settings = 3;</code>
     * @param ProxyConfig $var
     * @return $this
     */
    public function setProxySettings($var)
    {
        GPBUtil::checkMessage($var, ProxyConfig::class);
        $this->proxy_settings = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.app.proxyman.MultiplexingConfig multiplex_settings = 4;</code>
     * @return MultiplexingConfig|null
     */
    public function getMultiplexSettings()
    {
        return $this->multiplex_settings;
    }

    public function hasMultiplexSettings()
    {
        return isset($this->multiplex_settings);
    }

    public function clearMultiplexSettings()
    {
        unset($this->multiplex_settings);
    }

    /**
     * Generated from protobuf field <code>.xray.app.proxyman.MultiplexingConfig multiplex_settings = 4;</code>
     * @param MultiplexingConfig $var
     * @return $this
     */
    public function setMultiplexSettings($var)
    {
        GPBUtil::checkMessage($var, MultiplexingConfig::class);
        $this->multiplex_settings = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string via_cidr = 5;</code>
     * @return string
     */
    public function getViaCidr()
    {
        return $this->via_cidr;
    }

    /**
     * Generated from protobuf field <code>string via_cidr = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setViaCidr($var)
    {
        GPBUtil::checkString($var, True);
        $this->via_cidr = $var;

        return $this;
    }

}

