<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/proxyman/config.proto

namespace Xray\App\Proxyman;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.app.proxyman.SniffingConfig</code>
 */
class SniffingConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Whether or not to enable content sniffing on an inbound connection.
     *
     * Generated from protobuf field <code>bool enabled = 1;</code>
     */
    protected $enabled = false;
    /**
     * Override target destination if sniff'ed protocol is in the given list.
     * Supported values are "http", "tls", "fakedns".
     *
     * Generated from protobuf field <code>repeated string destination_override = 2;</code>
     */
    private $destination_override;
    /**
     * Generated from protobuf field <code>repeated string domains_excluded = 3;</code>
     */
    private $domains_excluded;
    /**
     * Whether should only try to sniff metadata without waiting for client input.
     * Can be used to support SMTP like protocol where server send the first
     * message.
     *
     * Generated from protobuf field <code>bool metadata_only = 4;</code>
     */
    protected $metadata_only = false;
    /**
     * Generated from protobuf field <code>bool route_only = 5;</code>
     */
    protected $route_only = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $enabled
     *           Whether or not to enable content sniffing on an inbound connection.
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $destination_override
     *           Override target destination if sniff'ed protocol is in the given list.
     *           Supported values are "http", "tls", "fakedns".
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $domains_excluded
     *     @type bool $metadata_only
     *           Whether should only try to sniff metadata without waiting for client input.
     *           Can be used to support SMTP like protocol where server send the first
     *           message.
     *     @type bool $route_only
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Proxyman\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Whether or not to enable content sniffing on an inbound connection.
     *
     * Generated from protobuf field <code>bool enabled = 1;</code>
     * @return bool
     */
    public function getEnabled()
    {
        return $this->enabled;
    }

    /**
     * Whether or not to enable content sniffing on an inbound connection.
     *
     * Generated from protobuf field <code>bool enabled = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setEnabled($var)
    {
        GPBUtil::checkBool($var);
        $this->enabled = $var;

        return $this;
    }

    /**
     * Override target destination if sniff'ed protocol is in the given list.
     * Supported values are "http", "tls", "fakedns".
     *
     * Generated from protobuf field <code>repeated string destination_override = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDestinationOverride()
    {
        return $this->destination_override;
    }

    /**
     * Override target destination if sniff'ed protocol is in the given list.
     * Supported values are "http", "tls", "fakedns".
     *
     * Generated from protobuf field <code>repeated string destination_override = 2;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDestinationOverride($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->destination_override = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string domains_excluded = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDomainsExcluded()
    {
        return $this->domains_excluded;
    }

    /**
     * Generated from protobuf field <code>repeated string domains_excluded = 3;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDomainsExcluded($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->domains_excluded = $arr;

        return $this;
    }

    /**
     * Whether should only try to sniff metadata without waiting for client input.
     * Can be used to support SMTP like protocol where server send the first
     * message.
     *
     * Generated from protobuf field <code>bool metadata_only = 4;</code>
     * @return bool
     */
    public function getMetadataOnly()
    {
        return $this->metadata_only;
    }

    /**
     * Whether should only try to sniff metadata without waiting for client input.
     * Can be used to support SMTP like protocol where server send the first
     * message.
     *
     * Generated from protobuf field <code>bool metadata_only = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setMetadataOnly($var)
    {
        GPBUtil::checkBool($var);
        $this->metadata_only = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool route_only = 5;</code>
     * @return bool
     */
    public function getRouteOnly()
    {
        return $this->route_only;
    }

    /**
     * Generated from protobuf field <code>bool route_only = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setRouteOnly($var)
    {
        GPBUtil::checkBool($var);
        $this->route_only = $var;

        return $this;
    }

}

