<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/dns/fakedns/fakedns.proto

namespace GPBMetadata\App\Dns\Fakedns;

class Fakedns
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
”
app/dns/fakedns/fakedns.protoxray.app.dns.fakedns"/
FakeDnsPool
ip_pool (	
lruSize ("D
FakeDnsPoolMulti0
pools (2!.xray.app.dns.fakedns.FakeDnsPoolB^
com.xray.app.dns.fakednsPZ)github.com/xtls/xray-core/app/dns/fakednsªXray.App.Dns.Fakednsbproto3'
        , true);

        static::$is_initialized = true;
    }
}

