<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/policy/config.proto

namespace Xray\App\Policy;

if (false) {
    /**
     * This class is deprecated. Use Xray\App\Policy\Policy\Timeout instead.
     * @deprecated
     */
    class Policy_Timeout
    {
    }
}
class_exists(Policy\Timeout::class);
@trigger_error('Xray\App\Policy\Policy_Timeout is deprecated and will be removed in the next major release. Use Xray\App\Policy\Policy\Timeout instead', E_USER_DEPRECATED);

