<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/vless/outbound/config.proto

namespace GPBMetadata\Proxy\Vless\Outbound;

use Google\Protobuf\Internal\DescriptorPool;
use GPBMetadata\Common\Protocol\ServerSpec;

class Config
{
    public static $is_initialized = false;

    public static function initOnce()
    {
        $pool = DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
            return;
        }
        ServerSpec::initOnce();
        $pool->internalAddGeneratedFile(
            '
�
!proxy/vless/outbound/config.protoxray.proxy.vless.outbound"=
Config3
vnext (2$.xray.common.protocol.ServerEndpointBm
com.xray.proxy.vless.outboundPZ.github.com/xtls/xray-core/proxy/vless/outbound�Xray.Proxy.Vless.Outboundbproto3'
            , true);

        static::$is_initialized = true;
    }
}

