<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/http/config.proto

namespace Xray\Proxy\Http;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ClientConfig is the protobuf config for HTTP proxy client.
 *
 * Generated from protobuf message <code>xray.proxy.http.ClientConfig</code>
 */
class ClientConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Sever is a list of HTTP server addresses.
     *
     * Generated from protobuf field <code>repeated .xray.common.protocol.ServerEndpoint server = 1;</code>
     */
    private $server;
    /**
     * Generated from protobuf field <code>repeated .xray.proxy.http.Header header = 2;</code>
     */
    private $header;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Xray\Common\Protocol\ServerEndpoint>|\Google\Protobuf\Internal\RepeatedField $server
     *           Sever is a list of HTTP server addresses.
     *     @type array<\Xray\Proxy\Http\Header>|\Google\Protobuf\Internal\RepeatedField $header
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proxy\Http\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Sever is a list of HTTP server addresses.
     *
     * Generated from protobuf field <code>repeated .xray.common.protocol.ServerEndpoint server = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getServer()
    {
        return $this->server;
    }

    /**
     * Sever is a list of HTTP server addresses.
     *
     * Generated from protobuf field <code>repeated .xray.common.protocol.ServerEndpoint server = 1;</code>
     * @param array<\Xray\Common\Protocol\ServerEndpoint>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setServer($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xray\Common\Protocol\ServerEndpoint::class);
        $this->server = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.proxy.http.Header header = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.proxy.http.Header header = 2;</code>
     * @param array<\Xray\Proxy\Http\Header>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHeader($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xray\Proxy\Http\Header::class);
        $this->header = $arr;

        return $this;
    }

}

