<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/config.proto

namespace Xray\Transport\Internet;

if (false) {
    /**
     * This class is deprecated. Use Xray\Transport\Internet\SocketConfig\TProxyMode instead.
     * @deprecated
     */
    class SocketConfig_TProxyMode
    {
    }
}
class_exists(SocketConfig\TProxyMode::class);
@trigger_error('Xray\Transport\Internet\SocketConfig_TProxyMode is deprecated and will be removed in the next major release. Use Xray\Transport\Internet\SocketConfig\TProxyMode instead', E_USER_DEPRECATED);

