<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/config.proto

namespace Xray\Transport\Internet;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\Internal\RepeatedField;
use GPBMetadata\Transport\Internet\Config;
use Xray\Common\Serial\TypedMessage;

/**
 * Generated from protobuf message <code>xray.transport.internet.StreamConfig</code>
 */
class StreamConfig extends Message
{
    /**
     * Effective network.
     *
     * Generated from protobuf field <code>string protocol_name = 5;</code>
     */
    protected $protocol_name = '';
    /**
     * Generated from protobuf field <code>repeated .xray.transport.internet.TransportConfig transport_settings = 2;</code>
     */
    private $transport_settings;
    /**
     * Type of security. Must be a message name of the settings proto.
     *
     * Generated from protobuf field <code>string security_type = 3;</code>
     */
    protected $security_type = '';
    /**
     * Settings for transport security. For now the only choice is TLS.
     *
     * Generated from protobuf field <code>repeated .xray.common.serial.TypedMessage security_settings = 4;</code>
     */
    private $security_settings;
    /**
     * Generated from protobuf field <code>.xray.transport.internet.SocketConfig socket_settings = 6;</code>
     */
    protected $socket_settings = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * @type string $protocol_name
     *           Effective network.
     * @type array<TransportConfig>|RepeatedField $transport_settings
     * @type string $security_type
     *           Type of security. Must be a message name of the settings proto.
     * @type array<TypedMessage>|RepeatedField $security_settings
     *           Settings for transport security. For now the only choice is TLS.
     * @type SocketConfig $socket_settings
     * }
     */
    public function __construct($data = NULL)
    {
        Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Effective network.
     *
     * Generated from protobuf field <code>string protocol_name = 5;</code>
     * @return string
     */
    public function getProtocolName()
    {
        return $this->protocol_name;
    }

    /**
     * Effective network.
     *
     * Generated from protobuf field <code>string protocol_name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setProtocolName($var)
    {
        GPBUtil::checkString($var, True);
        $this->protocol_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.transport.internet.TransportConfig transport_settings = 2;</code>
     * @return RepeatedField
     */
    public function getTransportSettings()
    {
        return $this->transport_settings;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.transport.internet.TransportConfig transport_settings = 2;</code>
     * @param array<TransportConfig>|RepeatedField $var
     * @return $this
     */
    public function setTransportSettings($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, TransportConfig::class);
        $this->transport_settings = $arr;

        return $this;
    }

    /**
     * Type of security. Must be a message name of the settings proto.
     *
     * Generated from protobuf field <code>string security_type = 3;</code>
     * @return string
     */
    public function getSecurityType()
    {
        return $this->security_type;
    }

    /**
     * Type of security. Must be a message name of the settings proto.
     *
     * Generated from protobuf field <code>string security_type = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSecurityType($var)
    {
        GPBUtil::checkString($var, True);
        $this->security_type = $var;

        return $this;
    }

    /**
     * Settings for transport security. For now the only choice is TLS.
     *
     * Generated from protobuf field <code>repeated .xray.common.serial.TypedMessage security_settings = 4;</code>
     * @return RepeatedField
     */
    public function getSecuritySettings()
    {
        return $this->security_settings;
    }

    /**
     * Settings for transport security. For now the only choice is TLS.
     *
     * Generated from protobuf field <code>repeated .xray.common.serial.TypedMessage security_settings = 4;</code>
     * @param array<TypedMessage>|RepeatedField $var
     * @return $this
     */
    public function setSecuritySettings($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, TypedMessage::class);
        $this->security_settings = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.SocketConfig socket_settings = 6;</code>
     * @return SocketConfig|null
     */
    public function getSocketSettings()
    {
        return $this->socket_settings;
    }

    public function hasSocketSettings()
    {
        return isset($this->socket_settings);
    }

    public function clearSocketSettings()
    {
        unset($this->socket_settings);
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.SocketConfig socket_settings = 6;</code>
     * @param SocketConfig $var
     * @return $this
     */
    public function setSocketSettings($var)
    {
        GPBUtil::checkMessage($var, SocketConfig::class);
        $this->socket_settings = $var;

        return $this;
    }

}

