<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/splithttp/config.proto

namespace Xray\Transport\Internet\Splithttp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.transport.internet.splithttp.RandRangeConfig</code>
 */
class RandRangeConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 from = 1;</code>
     */
    protected $from = 0;
    /**
     * Generated from protobuf field <code>int32 to = 2;</code>
     */
    protected $to = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $from
     *     @type int $to
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transport\Internet\Splithttp\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 from = 1;</code>
     * @return int
     */
    public function getFrom()
    {
        return $this->from;
    }

    /**
     * Generated from protobuf field <code>int32 from = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setFrom($var)
    {
        GPBUtil::checkInt32($var);
        $this->from = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 to = 2;</code>
     * @return int
     */
    public function getTo()
    {
        return $this->to;
    }

    /**
     * Generated from protobuf field <code>int32 to = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTo($var)
    {
        GPBUtil::checkInt32($var);
        $this->to = $var;

        return $this;
    }

}

