<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/shadowsocks/config.proto

namespace Xray\Proxy\Shadowsocks;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\Internal\RepeatedField;
use GPBMetadata\Proxy\Shadowsocks\Config;
use Xray\Common\Net\Network;
use Xray\Common\Protocol\User;

/**
 * Generated from protobuf message <code>xray.proxy.shadowsocks.ServerConfig</code>
 */
class ServerConfig extends Message
{
    /**
     * Generated from protobuf field <code>repeated .xray.common.protocol.User users = 1;</code>
     */
    private $users;
    /**
     * Generated from protobuf field <code>repeated .xray.common.net.Network network = 2;</code>
     */
    private $network;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * @type array<User>|RepeatedField $users
     * @type array<int>|RepeatedField $network
     * }
     */
    public function __construct($data = NULL)
    {
        Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.protocol.User users = 1;</code>
     * @return RepeatedField
     */
    public function getUsers()
    {
        return $this->users;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.protocol.User users = 1;</code>
     * @param array<User>|RepeatedField $var
     * @return $this
     */
    public function setUsers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, User::class);
        $this->users = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.net.Network network = 2;</code>
     * @return RepeatedField
     */
    public function getNetwork()
    {
        return $this->network;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.net.Network network = 2;</code>
     * @param array<int>|RepeatedField $var
     * @return $this
     */
    public function setNetwork($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::ENUM, Network::class);
        $this->network = $arr;

        return $this;
    }

}

