<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/vless/inbound/config.proto

namespace GPBMetadata\Proxy\Vless\Inbound;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Protocol\User::initOnce();
        $pool->internalAddGeneratedFile(
            '
“
 proxy/vless/inbound/config.protoxray.proxy.vless.inbound"^
Fallback
name (	
alpn (	
path (	
type (	
dest (	
xver ("€
Config+
clients (2.xray.common.protocol.User

decryption (	5
	fallbacks (2".xray.proxy.vless.inbound.FallbackBj
com.xray.proxy.vless.inboundPZ-github.com/xtls/xray-core/proxy/vless/inboundªXray.Proxy.Vless.Inboundbproto3'
        , true);

        static::$is_initialized = true;
    }
}

