<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/wireguard/config.proto

namespace Xray\Proxy\Wireguard\DeviceConfig;

use UnexpectedValueException;

/**
 * Protobuf type <code>xray.proxy.wireguard.DeviceConfig.DomainStrategy</code>
 */
class DomainStrategy
{
    /**
     * Generated from protobuf enum <code>FORCE_IP = 0;</code>
     */
    const FORCE_IP = 0;
    /**
     * Generated from protobuf enum <code>FORCE_IP4 = 1;</code>
     */
    const FORCE_IP4 = 1;
    /**
     * Generated from protobuf enum <code>FORCE_IP6 = 2;</code>
     */
    const FORCE_IP6 = 2;
    /**
     * Generated from protobuf enum <code>FORCE_IP46 = 3;</code>
     */
    const FORCE_IP46 = 3;
    /**
     * Generated from protobuf enum <code>FORCE_IP64 = 4;</code>
     */
    const FORCE_IP64 = 4;

    private static $valueToName = [
        self::FORCE_IP => 'FORCE_IP',
        self::FORCE_IP4 => 'FORCE_IP4',
        self::FORCE_IP6 => 'FORCE_IP6',
        self::FORCE_IP46 => 'FORCE_IP46',
        self::FORCE_IP64 => 'FORCE_IP64',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(DomainStrategy::class, \Xray\Proxy\Wireguard\DeviceConfig_DomainStrategy::class);

