<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/policy/config.proto

namespace Xray\App\Policy\Policy;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use GPBMetadata\App\Policy\Config;
use Xray\App\Policy\Policy_Stats;

/**
 * Generated from protobuf message <code>xray.app.policy.Policy.Stats</code>
 */
class Stats extends Message
{
    /**
     * Generated from protobuf field <code>bool user_uplink = 1;</code>
     */
    protected $user_uplink = false;
    /**
     * Generated from protobuf field <code>bool user_downlink = 2;</code>
     */
    protected $user_downlink = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * @type bool $user_uplink
     * @type bool $user_downlink
     * }
     */
    public function __construct($data = NULL)
    {
        Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool user_uplink = 1;</code>
     * @return bool
     */
    public function getUserUplink()
    {
        return $this->user_uplink;
    }

    /**
     * Generated from protobuf field <code>bool user_uplink = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setUserUplink($var)
    {
        GPBUtil::checkBool($var);
        $this->user_uplink = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool user_downlink = 2;</code>
     * @return bool
     */
    public function getUserDownlink()
    {
        return $this->user_downlink;
    }

    /**
     * Generated from protobuf field <code>bool user_downlink = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setUserDownlink($var)
    {
        GPBUtil::checkBool($var);
        $this->user_downlink = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Stats::class, Policy_Stats::class);

