<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/websocket/config.proto

namespace GPBMetadata\Transport\Internet\Websocket;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
¦
)transport/internet/websocket/config.proto!xray.transport.internet.websocket"Å
Config
host (	
path (	E
header (25.xray.transport.internet.websocket.Config.HeaderEntry
accept_proxy_protocol (

ed (-
HeaderEntry
key (	
value (	:8B…
%com.xray.transport.internet.websocketPZ6github.com/xtls/xray-core/transport/internet/websocketª!Xray.Transport.Internet.Websocketbproto3'
        , true);

        static::$is_initialized = true;
    }
}

