<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/dns/config.proto

namespace GPBMetadata\Proxy\Dns;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Net\Destination::initOnce();
        $pool->internalAddGeneratedFile(
            '
ò
proxy/dns/config.protoxray.proxy.dns"r
Config)
server (2.xray.common.net.Endpoint

user_level (
non_IP_query (	
block_types (BL
com.xray.proxy.dnsPZ#github.com/xtls/xray-core/proxy/dnsªXray.Proxy.Dnsbproto3'
        , true);

        static::$is_initialized = true;
    }
}

