<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/net/port.proto

namespace GPBMetadata\Common\Net;

class Port
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ß
common/net/port.protoxray.common.net"%
	PortRange
From (

To ("5
PortList)
range (2.xray.common.net.PortRangeBO
com.xray.common.netPZ$github.com/xtls/xray-core/common/netªXray.Common.Netbproto3'
        , true);

        static::$is_initialized = true;
    }
}

