<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/httpupgrade/config.proto

namespace GPBMetadata\Transport\Internet\Httpupgrade;

use Google\Protobuf\Internal\DescriptorPool;

class Config
{
    public static $is_initialized = false;

    public static function initOnce()
    {
        $pool = DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
            return;
        }
        $pool->internalAddGeneratedFile(
            '
�
+transport/internet/httpupgrade/config.proto#xray.transport.internet.httpupgrade"�
Config
host (	
path (	G
header (27.xray.transport.internet.httpupgrade.Config.HeaderEntry
accept_proxy_protocol (

ed (
-
HeaderEntry
key (	
value (	:8B�
\'com.xray.transport.internet.httpupgradePZ8github.com/xtls/xray-core/transport/internet/httpupgrade�#Xray.Transport.Internet.HttpUpgradebproto3'
            , true);

        static::$is_initialized = true;
    }
}

